const getItems = () => {
    return [
        {name: 'Anarchy', tier: 1, type: 'Shotgun'},
        {name: 'Lob', tier: 1, type: 'Shotgun'},
        {name: 'Recursion', tier: 1, type: 'Shotgun'},
        {name: 'Boom Sickle', tier: 1, type: 'AR'},
        {name: 'Good Juju', tier: 1, type: 'AR'},
        {name: 'Kaos', tier: 1, type: 'AR'},
        {name: 'Soulrender', tier: 1, type: 'AR'},
        {name: 'Cutsman', tier: 1, type: 'SMG'},
        {name: 'Hyperfocus XZ41', tier: 1, type: 'SMG'},
        {name: 'Kybs Worth', tier: 1, type: 'SMG'},
        {name: 'Redistributor', tier: 1, type: 'SMG'},
        {name: 'Hellshock', tier: 1, type: 'Pistol'},
        {name: 'Love Drill', tier: 1, type: 'Pistol'},
        {name: 'Maggie', tier: 1, type: 'Pistol'},
        {name: 'Moonfire', tier: 1, type: 'Pistol'},
        {name: 'Ion Cannon', tier: 1, type: 'Rocket Launcher'},
        {name: 'Krakatoa', tier: 1, type: 'Sniper'},
        {name: 'Cocky Bastard', tier: 1, type: 'Sniper'},
        {name: 'Unseen Threat', tier: 1, type: 'Sniper'},
        {name: 'Wedding Invitation', tier: 1, type: 'Sniper'},
        {name: 'Hex', tier: 1, type: 'Grenade'},
        {name: 'It\'s Piss', tier: 1, type: 'Grenade'},
        {name: 'Quasar', tier: 1, type: 'Grenade'},
        {name: 'Storm Front', tier: 1, type: 'Grenade'},
        {name: 'Band of Sitorak', tier: 1, type: 'Shield'},
        {name: 'Big Boom Blaster', tier: 1, type: 'Shield'},
        {name: 'Rico', tier: 1, type: 'Shield'},
        {name: 'Stop-Gap', tier: 1, type: 'Shield'},
        {name: 'The Transformer', tier: 1, type: 'Shield'},

        {name: 'Brainstormer', tier: 2, type: 'Shotgun'},
        {name: 'Conference Call', tier: 2, type: 'Shotgun'},
        {name: 'Flama Diddle', tier: 2, type: 'Shotgun'},
        {name: 'Garcia', tier: 2, type: 'Shotgun'},
        {name: 'Insider', tier: 2, type: 'Shotgun'},
        {name: 'Nothingness', tier: 2, type: 'Shotgun'},
        {name: 'Nimble Jack', tier: 2, type: 'Shotgun'},
        {name: 'One Pump Chump', tier: 2, type: 'Shotgun'},
        {name: 'Shocker', tier: 2, type: 'Shotgun'},
        {name: 'Tiggs Boom', tier: 2, type: 'Shotgun'},
        {name: 'Bekah', tier: 2, type: 'AR'},
        {name: 'Breath of the Dying', tier: 2, type: 'AR'},
        {name: 'Carrier', tier: 2, type: 'AR'},
        {name: 'Clairvoyance', tier: 2, type: 'AR'},
        {name: 'Damned', tier: 2, type: 'AR'},
        {name: 'Dictator', tier: 2, type: 'AR'},
        {name: 'Star Helix', tier: 2, type: 'AR'},
        {name: 'Starous Burn', tier: 2, type: 'AR'},
        {name: 'Embers Purge', tier: 2, type: 'SMG'},
        {name: 'EM-P5', tier: 2, type: 'SMG'},
        {name: 'Ion Laser', tier: 2, type: 'SMG'},
        {name: 'Night Hawkin', tier: 2, type: 'SMG'},
        {name: 'Oldridion', tier: 2, type: 'SMG'},
        {name: 'Sleeping Giant', tier: 2, type: 'SMG'},
        {name: 'Frozen Devil', tier: 2, type: 'Pistol'},
        {name: 'Little Yeeti', tier: 2, type: 'Pistol'},
        {name: 'Lucky 7', tier: 2, type: 'Pistol'},
        {name: 'Seventh Sense', tier: 2, type: 'Pistol'},
        {name: 'Wagon Wheel', tier: 2, type: 'Pistol'},
        {name: 'Scourge', tier: 2, type: 'Rocket Launcher'},
        {name: 'Fire Storm', tier: 2, type: 'Sniper'},
        {name: 'Headsplosion', tier: 2, type: 'Sniper'},
        {name: 'Lyuda', tier: 2, type: 'Sniper'},
        {name: 'Storm', tier: 2, type: 'Sniper'},
        {name: 'Tankmans Shield', tier: 2, type: 'Sniper'},
        {name: 'Woodblocker', tier: 2, type: 'Sniper'},
        {name: 'EMP', tier: 2, type: 'Grenade'},
        {name: 'Epicenter', tier: 2, type: 'Grenade'},
        {name: 'Hunter-Seeker', tier: 2, type: 'Grenade'},
        {name: 'Firestorm', tier: 2, type: 'Grenade'},
        {name: 'Surge', tier: 2, type: 'Grenade'},
        {name: 'Front Loader', tier: 2, type: 'Shield'},
        {name: 'Re-Charger', tier: 2, type: 'Shield'},
        {name: 'Red Suit', tier: 2, type: 'Shield'},
        {name: 'Version 0.m', tier: 2, type: 'Shield'},
        {name: 'Re-Charge Berner', tier: 2, type: 'Shield'},
        {name: 'Back Ham', tier: 2, type: 'Shield'},

        {name: 'Butcher', tier: 3, type: 'Shotgun'},
        {name: 'Face Puncher', tier: 3, type: 'Shotgun'},
        {name: 'Flakker', tier: 3, type: 'Shotgun'},
        {name: 'Hellwalker', tier: 3, type: 'Shotgun'},
        {name: 'Kill-O-The-Wisp', tier: 3, type: 'Shotgun'},
        {name: 'Polyaimorous', tier: 3, type: 'Shotgun'},
        {name: 'Redline', tier: 3, type: 'Shotgun'},
        {name: 'Trevonator', tier: 3, type: 'Shotgun'},
        {name: 'Alchemist', tier: 3, type: 'AR'},
        {name: 'Faisor', tier: 3, type: 'AR'},
        {name: 'Juliets Dazzle', tier: 3, type: 'AR'},
        {name: 'Laser Sploder', tier: 3, type: 'AR'},
        {name: 'Lucians Call', tier: 3, type: 'AR'},
        {name: 'Ogre', tier: 3, type: 'AR'},
        {name: 'Rowans Call', tier: 3, type: 'AR'},
        {name: 'Shredifier', tier: 3, type: 'AR'},
        {name: 'Seeryul Killer', tier: 3, type: 'AR'},
        {name: 'Zheitsevs Eruption', tier: 3, type: 'AR'},
        {name: 'Crossroads', tier: 3, type: 'SMG'},
        {name: 'Devoted', tier: 3, type: 'SMG'},
        {name: 'Tsunami', tier: 3, type: 'SMG'},
        {name: 'Westergun', tier: 3, type: 'SMG'},
        {name: 'AAA', tier: 3, type: 'Pistol'},
        {name: 'Craps', tier: 3, type: 'Pistol'},
        {name: 'Duc', tier: 3, type: 'Pistol'},
        {name: 'Hydrafrost', tier: 3, type: 'Pistol'},
        {name: 'Kings Call', tier: 3, type: 'Pistol'},
        {name: 'Linoge', tier: 3, type: 'Pistol'},
        {name: 'Nemesis', tier: 3, type: 'Pistol'},
        {name: 'Queens Call', tier: 3, type: 'Pistol'},
        {name: 'Roisens Thorns', tier: 3, type: 'Pistol'},
        {name: 'Scoville', tier: 3, type: 'Pistol'},
        {name: 'Skeksil', tier: 3, type: 'Pistol'},
        {name: 'Nukem', tier: 3, type: 'Rocket Launcher'},
        {name: 'Rubys Wrath', tier: 3, type: 'Rocket Launcher'},
        {name: 'Tunguska', tier: 3, type: 'Rocket Launcher'},
        {name: 'Monocle', tier: 3, type: 'Sniper'},
        {name: 'Tinas Hippity Hopper', tier: 3, type: 'Grenade'},
        {name: 'Transfusion', tier: 3, type: 'Grenade'},
        {name: 'Widow Maker', tier: 3, type: 'Grenade'},
        {name: 'Frozen Heart', tier: 3, type: 'Shield'},
        {name: 'Frozen Snowshoe', tier: 3, type: 'Shield'},
        {name: 'Messy Breakup', tier: 3, type: 'Shield'},
        {name: 'Ward', tier: 3, type: 'Shield'},

        {name: 'Boring Gun', tier: 4, type: 'Shotgun'},
        {name: 'Deathgrip', tier: 4, type: 'Shotgun'},
        {name: 'Fearmonger', tier: 4, type: 'Shotgun'},
        {name: 'Heart Breaker', tier: 4, type: 'Shotgun'},
        {name: 'Horizon', tier: 4, type: 'Shotgun'},
        {name: 'Phebert', tier: 4, type: 'Shotgun'},
        {name: 'Slow Hand', tier: 4, type: 'Shotgun'},
        {name: 'Tidal Wave', tier: 4, type: 'Shotgun'},
        {name: 'Barrage', tier: 4, type: 'AR'},
        {name: 'Embrace the Pain', tier: 4, type: 'AR'},
        {name: 'Gaitling Gun', tier: 4, type: 'AR'},
        {name: 'Lead Sprinkler', tier: 4, type: 'AR'},
        {name: 'More Pain Is Power', tier: 4, type: 'AR'},
        {name: 'Mutant', tier: 4, type: 'AR'},
        {name: 'Try-Bolt', tier: 4, type: 'AR'},
        {name: 'Warlord', tier: 4, type: 'AR'},
        {name: 'Bitch', tier: 4, type: 'SMG'},
        {name: 'Cheap Tips', tier: 4, type: 'SMG'},
        {name: 'Cloud Kill', tier: 4, type: 'SMG'},
        {name: 'Destructo Spinner', tier: 4, type: 'SMG'},
        {name: 'Handsome Jackhammer', tier: 4, type: 'SMG'},
        {name: 'Hellfire', tier: 4, type: 'SMG'},
        {name: 'SF Force', tier: 4, type: 'SMG'},
        {name: 'Smart Gun', tier: 4, type: 'SMG'},
        {name: '9-Volt', tier: 4, type: 'Pistol'},
        {name: 'Baby Maker', tier: 4, type: 'Pistol'},
        {name: 'Companion', tier: 4, type: 'Pistol'},
        {name: 'Devastator', tier: 4, type: 'Pistol'},
        {name: 'Devils Forsum', tier: 4, type: 'Pistol'},
        {name: 'Hornet', tier: 4, type: 'Pistol'},
        {name: 'Linc', tier: 4, type: 'Pistol'},
        {name: 'Pestilence', tier: 4, type: 'Pistol'},
        {name: 'Sellout', tier: 4, type: 'Pistol'},
        {name: 'Thunderball Fist', tier: 4, type: 'Pistol'},
        {name: 'Unforgiven', tier: 4, type: 'Pistol'},
        {name: 'Freeman', tier: 4, type: 'Rocket Launcher'},
        {name: 'Hive', tier: 4, type: 'Rocket Launcher'},
        {name: 'Maleks Bane', tier: 4, type: 'Sniper'},
        {name: 'Mind Killer', tier: 4, type: 'Sniper'},
        {name: 'Chupa\'s Organ', tier: 4, type: 'Grenade'},
        {name: 'Nagata', tier: 4, type: 'Grenade'},
        {name: 'Black Hole', tier: 4, type: 'Shield'},
        {name: 'Impaler', tier: 4, type: 'Shield'},
        {name: 'Nova Berner', tier: 4, type: 'Shield'},
        {name: 'Rough Rider', tier: 4, type: 'Shield'},
        {name: 'Shooting Star', tier: 4, type: 'Shield'},

        {name: 'Polybius', tier: 5, type: 'Shotgun'},
        {name: 'Sledges Shotgun', tier: 5, type: 'Shotgun'},
        {name: 'Turbo Ten Gallon', tier: 5, type: 'Shotgun'},
        {name: 'Rebel Yell', tier: 5, type: 'AR'},
        {name: 'Boomer', tier: 5, type: 'SMG'},
        {name: 'Muskett', tier: 5, type: 'SMG'},
        {name: 'Predatory Lending', tier: 5, type: 'SMG'},
        {name: 'Ripper', tier: 5, type: 'SMG'},
        {name: 'Vault Hero', tier: 5, type: 'SMG'},
        {name: 'Amazing Grace', tier: 5, type: 'Pistol'},
        {name: 'Bangarang', tier: 5, type: 'Pistol'},
        {name: 'Breeder', tier: 5, type: 'Pistol'},
        {name: 'Echo', tier: 5, type: 'Pistol'},
        {name: 'Flood', tier: 5, type: 'Pistol'},
        {name: 'Gunerang', tier: 5, type: 'Pistol'},
        {name: 'Infinity', tier: 5, type: 'Pistol'},
        {name: 'Magnificient', tier: 5, type: 'Pistol'},
        {name: 'Night Flyer', tier: 5, type: 'Pistol'},
        {name: 'Occultist', tier: 5, type: 'Pistol'},
        {name: 'Psycho Stabber', tier: 5, type: 'Pistol'},
        {name: 'Superball', tier: 5, type: 'Pistol'},
        {name: 'Creamer', tier: 5, type: 'Rocket Launcher'},
        {name: 'Jericho', tier: 5, type: 'Rocket Launcher'},
        {name: 'Quadomizer', tier: 5, type: 'Rocket Launcher'},
        {name: 'Auto Aime', tier: 5, type: 'Sniper'},
        {name: 'Masterwork Crossbow', tier: 5, type: 'Sniper'},
        {name: 'Red Queen', tier: 5, type: 'Grenade'},
        {name: 'Moxxis Bouncing Pair', tier: 5, type: 'Grenade'},
        {name: 'Ghast Call', tier: 5, type: 'Grenade'},
        {name: 'Rectifier', tier: 5, type: 'Shield'},

        {name: 'Creeping Death', tier: 6, type: 'Shotgun'},
        {name: 'TKs Wave', tier: 6, type: 'Shotgun'},
        {name: 'Bearcat', tier: 6, type: 'AR'},
        {name: 'Hand of Glory', tier: 6, type: 'AR'},
        {name: 'Sawbar', tier: 6, type: 'AR'},
        {name: 'Vanquisher', tier: 6, type: 'SMG'},
        {name: 'Girth Blaser', tier: 6, type: 'Pistol'},
        {name: 'Hyper-Hydrator', tier: 6, type: 'Pistol'},
        {name: 'Scorpio', tier: 6, type: 'Pistol'},
        {name: 'ASMD', tier: 6, type: 'Sniper'},
        {name: 'Cheddar Shredder', tier: 6, type: 'Grenade'},
        {name: 'Diamon Butt Bomb', tier: 6, type: 'Grenade'},
        {name: 'Fastball', tier: 6, type: 'Grenade'},
        {name: 'Scream of Terror', tier: 6, type: 'Shield'},
        {name: 'Whisker Tango Foxtrot', tier: 6, type: 'Shield'},
    ];
};

export const getTiers = () => {
    return [
        {name: 'Top Tier', tier: 1, color: '#FF0001'},
        {name: 'Awesome', tier: 2, color: '#FBB307'},
        {name: 'Great', tier: 3, color: '#8E07FF'},
        {name: 'Good', tier: 4, color: '#397AF2'},
        {name: 'Meh', tier: 5, color: '#2E9E49'},
        {name: 'Straight Trash', tier: 6, color: '#D4D3D4'},
    ];
}

export const getTypes = () => {
    return ['Shotgun', 'AR', 'SMG', 'Pistol', 'Rocket Launcher', 'Sniper', 'Grenade', 'Shield'];
}

export default getItems;