const getItems = () => {
    return [
        {name: 'Anarchy', tier: 1, type: 'Shotgun', dedicated: 'World Drop Only', location: 'DLC 2', area: '', redText: 'The stacks... THE STACKS!', ability: 'Auto reload or kill grants 30% dmg & reduces accuracy. Max 10 stacks', elements: 'Any'},
        {name: 'Insider', tier: 1, type: 'Shotgun', dedicated: 'World Drop Only', location: 'DLC 2', area: '', redText: 'You can run, but you cant hide.', ability: 'No charge time. Shots penetrate enemies', elements: 'F C S R O'},
        {name: 'Lob', tier: 1, type: 'Shotgun', dedicated: 'Graveward', location: 'Eden-6', area: 'The Floating Tomb', redText: 'Everything has to be magical.', ability: '3-round burst of big slow orbs that pass through enemies', elements: 'F C S R O'},
        {name: 'Recursion', tier: 1, type: 'Shotgun', dedicated: 'General Traunt', location: 'Nekrotafeyo', area: 'Desolations Edge', redText: 'See green text for description | See red text for description', ability: 'Shoots a disk that ricochets off walls', elements: 'Any'},
        {name: 'Reflux', tier: 1, type: 'Shotgun', m6: true, dedicated: 'GenIVIV', location: 'Eden-6', area: 'Voracious Canopy', redText: 'That\'s gotta burn.', ability: 'Corrodes nearby enemies. Biohazard projectile patttern (similar to the Brainstormer)', elements: 'C'},
        {name: 'Boom Sickle', tier: 1, type: 'AR', dedicated: 'Warden', location: 'Eden-6', area: 'The Anvil', redText: 'Swing the sickle!', ability: 'Its really a Full-Auto shotgun. Spread forms a sickle. 2 ammo/shot', elements: 'Any'},
        {name: 'Good Juju', tier: 1, type: 'AR', dedicated: 'The Rampager,Valkyrie Squad / Wotan', location: 'Promethea,', area: 'Forgotten Basilica,Midnights Cairn', m4: true, redText: 'Kinda, sorta wants to end all existence.', ability: 'Refills magazine on kill', elements: 'Any'},
        {name: 'Kaos', tier: 1, type: 'AR', dedicated: 'Psychobillies', location: 'Eden-6', area: 'Ambermire', redText: 'Grants the mystical art of exploding smallhands.', ability: 'Enemies explode on death. Explosion matches element', elements: 'F C S O'},
        {name: 'OPQ System', tier: 1, type: 'AR', dedicated: 'Joey Ultraviolet,Josie Byte,Franco Firewall', location: 'Revenge of the Cartels Event,Revenge of the Cartels Event,Revenge of the Cartels Event', area: 'Villa Ultraviolet,Villa Ultraviolet,Villa Ultraviolet', redText: 'B.Y.O.B.B', ability: 'Alternate fire: Spawns a drone copy of itself that targets where you aim', elements: 'N'},
        {name: 'Soulrender', tier: 1, type: 'AR', dedicated: 'Tom & Xam', location: 'Xylourgos', area: 'Hearts Desire', redText: 'Picture a soul. Now REND that thing!', ability: 'Sends out homing purple ghosts while firing that explode on impact', elements: 'Any'},
        {name: 'Cutsman', tier: 1, type: 'SMG', dedicated: 'Borman Nates', location: 'Promethea', area: 'Meridian Outskirts', redText: 'Little android man, born without a soul.', ability: '[Bladed]. 2 ammo/shot', elements: 'F C S'},
        {name: 'Hyperfocus XZ41', tier: 1, type: 'SMG', dedicated: 'Power Troopers', location: 'Promethea', area: 'Atlas HQ', redText: 'My line has ended.', ability: 'Front shield reflects bullets back at attackers', elements: 'Any'},
        {name: 'Kaoson', tier: 1, type: 'SMG', m6: true, dedicated: 'Captain Traunt', location: 'Athenas', area: 'Athenas', redText: 'Small but packs a punch', ability: 'Sticky shots that explode on reload. +Splash dmg radius', elements: 'Any'},
        {name: 'Kybs Worth', tier: 1, type: 'SMG', dedicated: 'Wotan the Invincible', area: 'Midnights Cairn', redText: 'Stand in the f****** circle.', ability: 'Fallen enemies spawn a Healing Aura once every 10 seconds', elements: 'Any'},
        {name: 'Redistributor', tier: 1, type: 'SMG', dedicated: 'Valkyrie Squad / Wotan', area: 'Midnights Cairn', redText: 'Mans reach exceeds his imagination.', ability: 'Every 7th shot is Amped. Amped shots chain to nearby enemies', elements: 'F C S R O'},
        {name: 'Hellshock', tier: 1, type: 'Pistol', dedicated: 'Gigamind', location: 'Promethea', area: 'Meridian Metroplex', redText: 'I had not thought death had undone so many.', ability: '2 projectiles/shot. Ricochet switches projectile element', elements: 'F S'},
        {name: 'Love Drill', tier: 1, type: 'Pistol', dedicated: 'Eleanor and the Heart', location: 'Xylourgos', area: 'Hearts Desire', redText: '...till death us depart.', ability: '20% chance to deal double dmg as shock dmg', elements: 'N'},
        {name: 'Maggie', tier: 1, type: 'Pistol', dedicated: 'Tremendous Rex', location: 'Promethea (Meridian Metroplex)', area: 'Cistern of Slaughter', redText: 'Montys wife dont take no guff.', ability: '6 pellets per shot. Low accuracy', elements: 'N'},
        {name: 'Moonfire', tier: 1, type: 'Pistol', dedicated: 'Wotan the Invincible', area: 'Midnights Cairn', redText: 'Meet your destiny.', ability: 'Every 3rd shot is a powerful shot', elements: 'Any'},
        {name: 'Ion Cannon', tier: 1, type: 'Rocket Launcher', dedicated: 'Fabricator', location: 'The Handsome Jackpot', area: 'Jacks Secret', redText: 'Fun Detected: Obliterate.', ability: 'Charging shot releases fast rocket. 6 ammo/shot', elements: 'Any'},
        {name: 'Yellowcake', tier: 1, type: 'Rocket Launcher', dedicated: 'Joey Ultraviolet,FISH SLAP!!!,Tyrone Smallums', location: 'Revenge of the Cartels Event,Revenge of the Cartels Event,Revenge of the Cartels Event', area: 'Villa Ultraviolet,Villa Ultraviolet,Villa Ultraviolet', redText: 'I\'m really more of a pie person.', ability: 'Splits into 4 balls that drop and explode. High splash radius', elements: 'R'},
        {name: 'Krakatoa', tier: 1, type: 'Sniper', dedicated: 'The Rampager', location: 'Promethea', area: 'Forgotten Basilica', redText: 'Get him angry and hes bound to erupt', ability: 'Turns killed enemies into volcanoes (must be on ground). Full-Auto', elements: 'F'},
        {name: 'Cocky Bastard', tier: 1, type: 'Sniper', dedicated: 'DLC 2 Chests', location: 'Xylourgos', area: 'All', redText: 'Great, kid.', ability: 'Crit deals additional +100% dmg as shock dmg', elements: 'N'},
        {name: 'Unseen Threat', tier: 1, type: 'Sniper', dedicated: 'Amach', location: 'Xylourgos', area: 'Cursehaven', redText: 'Taste their fear.', ability: 'Crit ricochets 3 homing projectiles', elements: 'N'},
        {name: 'Sand Hawk', tier: 1, type: 'Sniper', m6: true, dedicated: 'Katagawa Jr', location: 'Promethea', area: 'Atlas HQ', redText: 'Wedge a pig.', ability: 'Fires a line of nine projectiles. Semi-auto & tight spread / 3-round burst & wide spread', elements: 'Any'},
        {name: 'Skullmasher', tier: 1, type: 'Sniper', dedicated: 'Eista', location: 'Xylourgos', area: 'Skittermaw Basin', redText: 'Makes your brain hurt.', ability: 'x5 projectiles per shot. Extremely fast fire rate', elements: 'N'},
        {name: 'Wedding Invitation', tier: 1, type: 'Sniper', dedicated: '100 Broken Hearts', location: 'Special Event', area: '', redText: 'Will you be the rest of my life?', ability: 'Shoots as fire, ricochets as cryo. Crit returns 1 bullet', elements: 'F O'},
        {name: 'Hex', tier: 1, type: 'Grenade', dedicated: 'Sky Bullies', location: 'Eden-6', area: 'The Anvil', redText: 'Keeper of the stars, I hope to never find...', ability: 'Hovers around releasing beams of damage to nearby enemies', elements: 'S R O'},
        {name: 'Its Piss', tier: 1, type: 'Grenade', dedicated: 'Sloth', location: 'Pandora', area: 'Konrads Hold', redText: 'Hey you guys!', ability: 'Removes status effects on allies. Damaged enemies take +20% dmg', elements: 'N'},
        {name: 'Quasar', tier: 1, type: 'Grenade', dedicated: 'Wick and Warty', location: 'Promethea', area: 'Lectra City', redText: 'E=mc^(OMG)/wtf', ability: 'Hovers & sucks enemies in. Constant arcs of electricity', elements: 'S'},
        {name: 'Storm Front', tier: 1, type: 'Grenade', dedicated: 'El Dragon Jr.', location: 'Eden-6', area: 'Jakobs Estate', redText: 'Very, very frightening.', ability: 'Splits into 4 grenades that deal continuous shock to nearby enemies', elements: 'S'},
        {name: 'Band of Sitorak', tier: 1, type: 'Shield', dedicated: 'The Unstoppable', location: 'Eden-6', area: 'Ambermire', redText: 'I said "biiiiiiiiiiiitttccchhhh..."', ability: ' +22% wpn dmg while depleted. Low capacity, Very high recharge rate', elements: 'F C S R O'},
        {name: 'Big Boom Blaster', tier: 1, type: 'Shield', dedicated: 'The Unstoppable', location: 'Eden-6', area: 'Ambermire', redText: 'For all your big boom blasting needs!', ability: 'boosters restore 60% shield, grenade, & heavy ammo. 15% absorb', elements: 'Any'},
        {name: 'Firewall', tier: 1, type: 'Shield', dedicated: 'Joey Ultraviolet,Josie Byte,Franco Firewall', location: 'Revenge of the Cartels Event,Revenge of the Cartels Event,Revenge of the Cartels Event', area: 'Villa Ultraviolet,Villa Ultraviolet,Villa Ultraviolet', redText: 'Initiate countermeasures.', ability: 'Projected shield has a chance to fire projectiles at attackers. A portion of the projectiles damage restores shields.', elements: 'N'},
        {name: 'Rico', tier: 1, type: 'Shield', dedicated: 'Quest Reward', location: 'The Handsome Jackpot', area: 'VIP Tower', quest: 'All Bets Off', redText: 'You wanna live forever?', ability: '50% chance to reflect shots while shielded. 80% while not shielded', elements: 'N'},
        {name: 'Stop-Gap', tier: 1, type: 'Shield', dedicated: 'El Dragon Jr.', location: 'Eden-6', area: 'Jakobs Estate', redText: 'The process is called "living".', ability: 'Immune to dmg on depletion for 5 seconds', elements: 'Any'},
        {name: 'The Transformer', tier: 1, type: 'Shield', dedicated: 'Killavolt,Quest Reward', location: 'Promethea,Nekrotafeyo', area: 'Lectra City,Desolations Edge', quest: ',Its Alive', redText: 'Theres more than your eye can see.', ability: '100% Shock resistance. 40% chance to absorb bullets', elements: 'S'},
        {name: 'Wattson', tier: 1, type: 'Shield', dedicated: 'Joey Ultraviolet,FISH SLAP!!!,Tyrone Smallums', location: 'Revenge of the Cartels Event,Revenge of the Cartels Event,Revenge of the Cartels Event', area: 'Villa Ultraviolet,Villa Ultraviolet,Villa Ultraviolet', redText: 'Its all quite arbitrary, my dear boy.', ability: 'When damage is taken, fires discs that spawn in random elements and deal elemental damage', elements: 'N'},
        {name: 'Otto Idol', tier: 1, type: 'Artifact', dedicated: 'Tyreen the Destroyer', location: 'Pandora', area: 'Destroyers Rift', redText: 'Every man for himself.', ability: 'Restores +20% max HP per kill (lvl57)', elements: 'Any'},
        {name: 'Pearl of Ineffable Knowledge', tier: 1, type: 'Artifact', dedicated: 'Quest Reward', location: 'Xylourgos', area: 'The Lodge', quest: 'The Call of Gythian', redText: 'Knowing is half the battle.', ability: 'Consec. hits grant +1% dmg per hit up to 15 times. At max add +90%', elements: 'N'},
        {name: 'Victory Rush', tier: 1, type: 'Artifact', dedicated: 'Sloth', location: 'Pandora', area: 'Konrads Hold', redText: 'Another one.', ability: '+18% movement speed and dmg on badass kill for 60 seconds', elements: 'Any'},
        {name: 'Blast Master', tier: 1, type: 'Class Mod', character: 'Moze', dedicated: 'Arbalest of Discipline', location:'Precipice Anchor', quest: 'Trial of Discipline', redText: 'Slow and steady wins the arms race.', ability: 'The longer going without reloading, the more splash dmg Moze deals'},
        {name: 'Bounty Hunter', tier: 1, type: 'Class Mod', character: 'Fl4k', dedicated: 'Hag of Fervor', location: 'Skydrowned Pulpit', quest: 'Trial of Fervor', redText: 'The world is made up of two classes — the hunters and the huntees.', ability: '3% Hunt Kill Skill chance / Bosses as regular enemies'},
        {name: 'Seein Dead', tier: 1, type: 'Class Mod', character: 'Zane', dedicated: 'Quest Reward', location: 'The Handsome Jackpot', area: 'VIP Tower', quest: 'All Bets Off', redText: 'Musha rain dum a doo, dum a da.', ability: '4% chance to auto activ. all kill skills on wpn dmg. +25% Kill skill effect'},
        {name: 'Spiritual Driver', tier: 1, type: 'Class Mod', character: 'Amara', m4: true, dedicated: 'Sylestro,Wotan the Invincible', location: 'Nekrotafeyo,', area: 'Tazandeer Ruins,Midnights Cairn', redText: 'Only on the brink can we see so clearly.', ability: 'On Action Skill, apply skill element to self. +Gun dmg while moving'},

        {name: 'Brainstormer', tier: 2, type: 'Shotgun', dedicated: 'Katagawa Ball', location: 'Promethea', area: 'Skywell-27', redText: 'Lets put our heads together.', ability: 'Vertical row spread. Shocks nearby enemies', elements: 'S'},
        {name: 'Conference Call', tier: 2, type: 'Shotgun', dedicated: 'Judge Hightower', location: 'Promethea', area: 'Lectra City', redText: 'Lets just ping everyone all at once', ability: 'Spawns more projectiles. Same as in BL2', elements: 'Any'},
        {name: 'Garcia', tier: 2, type: 'Shotgun', dedicated: 'Chonk Stomp', location: 'Eden-6', area: 'Floodmoor Basin', redText: 'Rooty Tooty Pointy Shooty', ability: 'High mag size. 2 ammo/shot', elements: 'N'},
        {name: 'Nothingness', tier: 2, type: 'Shotgun', dedicated: 'Gmork', location: 'Xylourgos', area: 'The Cankerwood', redText: 'A hole would be something.', ability: 'Charged shot for several consecutive explosions (similar to the Flakker)', elements: 'F C S R O'},
        {name: 'Nimble Jack', tier: 2, type: 'Shotgun', dedicated: 'Handsome Jackie', location: 'Promethea', area: 'Skywell-27', redText: 'Jack be nimble, Jack be quick, Jack jump and kill lunatics.', ability: 'Tight spread. 1 shot reload', elements: 'N'},
        {name: 'One Pump Chump', tier: 2, type: 'Shotgun', dedicated: 'One Punch', location: 'Promethea', area: 'Lectra City', redText: 'I swear, that has never happened before.', ability: '50% chance to not consume ammo', elements: 'N'},
        {name: 'Shocker', tier: 2, type: 'Shotgun', dedicated: 'Voltborn', location: 'Xylourgos', area: 'Negul Neshai', redText: 'Everything has to be magical. Surprise!', ability: 'Shock orb that splits into 3 orbs horizontally', elements: 'S'},
        {name: 'Tiggs Boom', tier: 2, type: 'Shotgun', dedicated: 'Wotan the Invincible', area: 'Midnights Cairn', redText: 'A gaping hole in the sky.', ability: 'Shots pierce enemies. Makes meteors fall from the sky. 2 ammo/shot', elements: 'F C S R O'},
        {name: 'Alchemist', tier: 2, type: 'AR', dedicated: 'Heckle/Hyde', location: 'Eden-6', area: 'Jakobs Estate', redText: 'You cant gain something without giving something in return.', ability: 'Semi-Auto. Sticks as shock, explodes as fire. Damages user', elements: 'F S'},
        {name: 'Bekah', tier: 2, type: 'AR', dedicated: 'Sir Hammerlock Mail', quest: 'Hammerlocks Legendary Hunt 100%', redText: 'Shoot them in the face. Twice.', ability: 'Shot splits into 3 projectiles. Hits twice', elements: 'N'},
        {name: 'Breath of the Dying', tier: 2, type: 'AR', dedicated: 'Blinding Banshee', location: 'Nekrotafeyo', area: 'Desolations Edge', redText: 'VexHeIEIEIdZodEth', ability: 'Every kill spawns a radial burst of projectiles', elements: 'C'},
        {name: 'Carrier', tier: 2, type: 'AR', dedicated: 'Judge Hightower', location: 'Promethea', area: 'Lectra City', redText: 'I have arrived.', ability: 'On enemy impact, bullet splits in 2 and homes in on the same enemy', elements: 'N'},
        {name: 'Clairvoyance', tier: 2, type: 'AR', dedicated: 'Kritchy', location: 'Xylourgos', area: 'Cursehaven', redText: 'A broken smile beneath her whispered wings.', ability: 'Crit sticks projectiles which later explode', elements: 'O'},
        {name: 'Damned', tier: 2, type: 'AR', dedicated: 'Agonizer 9000', location: 'Pandora', area: 'Guts of Carnivora', redText: 'Well, I\'ll be...', ability: 'Weapon shield', elements: 'Any'},
        {name: 'Dictator', tier: 2, type: 'AR', dedicated: 'Agonizer 9000 & Pain', location: 'Pandora', area: 'Guts of Carnivora', redText: 'Let them hate me, so that they will but fear me.', ability: 'Full-Auto 3 projectiles / Bipod 7 projectiles. Fires in horizontal spread', elements: 'Any'},
        {name: 'The Monarch', tier: 2, type: 'AR', m6: true, dedicated: 'Killavolt', location: 'Promethea', area: 'Lectra City', redText: 'The deadly sting of the monarch!', ability: 'Shotgun AR (x4. x8 with right part). x2 dmg using bipod. High mag size & fire rate', elements: 'Any'},
        {name: 'Star Helix', tier: 2, type: 'AR', dedicated: 'Power Troopers', location: 'Promethea', area: 'Atlas HQ', redText: 'The stars are better off without us.', ability: 'Full-Auto / 4-round. Shoots a straight bullet between 2 weaving bullets', elements: 'N S R O'},
        {name: 'Stauros Burn', tier: 2, type: 'AR', dedicated: 'Wendigo', location: 'Xylourgos', area: 'The Cankerwood', redText: 'A long sigh was heard...', ability: 'Chance on break to combust. Combust = guarantees crit hits & +fire dmg', elements: 'F'},
        {name: 'Embers Purge', tier: 2, type: 'SMG', dedicated: 'Ember Mail', location: 'DLC 1', area: '', quest: 'Ember Challenge 100%', redText: 'Shes the only one who knows what it is to burn.', ability: '10% chance to create elemental puddle on enemy impact'},
        {name: 'EM-P5', tier: 2, type: 'SMG', m4: true, dedicated: 'Agonizer 9000 & Pain,Valkyrie Squad / Wotan', location: 'Pandora,', area: 'Guts of Carnivora,Midnights Cairn', redText: 'Dust off the beta EMP5.', ability: 'Increases movement speed while holding it. Increases accuracy while in the air.', elements: 'N'},
        {name: 'Ion Laser', tier: 2, type: 'SMG', dedicated: 'Evil Saint Lawrence', location: 'The Handsome Jackpot', area: 'The Spendopticon', redText: 'Particles unite!', ability: 'Continuous beam. Stop firing shoots orbs, count based on beam duration', elements: 'F C S R O'},
        {name: 'Night Hawkin', tier: 2, type: 'SMG', dedicated: 'Demoskaggons,Rakkman', location: 'Pandora,Pandora', area: 'The Droughts,Carnivora', redText: 'Stranger than things.', ability: 'Cryo during the day. Fire at night', elements: 'F/O'},
        {name: 'Oldridian', tier: 2, type: 'SMG', dedicated: 'World Drop Only', location: 'DLC 2', area: '', redText: 'They bound the ones they knew of. There were more.', ability: 'Switches element on reload. Weapon shield reduces elemental dmg 20%', elements: 'Any'},
        {name: 'Sleeping Giant', tier: 2, type: 'SMG', dedicated: 'One Punch', location: 'Promethea', area: 'Lectra City', redText: 'Infinite path carved with unrivaled skill.', ability: 'Reloading has a chance to grant weapon bonuses', elements: 'N F C S'},
        {name: 'Craps', tier: 2, type: 'Pistol', dedicated: 'Jackpot', location: 'The Handsome Jackpot', area: 'VIP Tower', redText: 'Oh, me.', ability: 'Chance to fire a circle of projectiles', elements: 'Any'},
        {name: 'Frozen Devil', tier: 2, type: 'Pistol', dedicated: 'Kukuwajack', location: 'Xylourgos', area: 'Negul Neshai', redText: 'Not sorry, not sorry, not sorry.', ability: 'Continuous laser / Ice Spike', elements: 'O'},
        {name: 'Lucky 7', tier: 2, type: 'Pistol', dedicated: 'Scraptrap Prime', location: 'The Handsome Jackpot', area: 'The Compactor', redText: 'O Fortuna.', ability: '25% chance for: crit, explosive, full-auto, ricochet, amp, or 7 projectiles', elements: 'N'},
        {name: 'Scoville', tier: 2, type: 'Pistol', dedicated: 'Torgue Mail', quest: 'Ember Challenge 100%', location: 'DLC 1', redText: 'Put a little pepper on the end of it.', ability: 'High splash radius. 5 ammo/shot', elements: 'F'},
        {name: 'Seventh Sense', tier: 2, type: 'Pistol', dedicated: 'Quest Reward', quest: 'Cold Case: Forgotten Answers', location: 'Xylourgos', area: 'The Cankerwood', redText: 'Something so close, and yet... so distant.', ability: 'Reloading causes all spawned projectiles to hit the original target', elements: 'O'},
        {name: 'Wagon Wheel', tier: 2, type: 'Pistol', dedicated: 'Warden,Loot-o-Gram', location: 'Eden-6,Promethea', area: 'The Anvil,Skywell-27', redText: 'Keep them doggies rollin.', ability: 'Ricochets 6 bullets off enemy', elements: 'N'},
        {name: 'Plague Bearer', tier: 2, type: 'Rocket Launcher', m6: true, dedicated: 'Warden', location: 'Eden-6', area: 'The Anvil', redText: 'Glad you could make it.', ability: 'Large slow moving orb that spawns additional orbs. Creates singularity. 3 ammo/shot', elements: 'Any'},
        {name: 'Scourge', tier: 2, type: 'Rocket Launcher', dedicated: 'Brood Mother,Alacritous Vanda', location: 'Nekrotafeyo', area: 'The Pyre of Stars,Cistern of Slaughter', redText: 'Or am I?', ability: 'Shoots 1 large rocket with 3 smaller swirling around it. 4 ammo/shot', elements: 'Any'},
        {name: 'Fire Storm', tier: 2, type: 'Sniper', dedicated: 'Katagawa Jr.', location: 'Promethea', area: 'Atlas HQ', redText: 'Seek shelter immediately.', ability: 'High splash radius. 2 ammo/shot.', elements: 'F'},
        {name: 'Headsplosion', tier: 2, type: 'Sniper', dedicated: 'Manvark', location: 'Pandora', area: 'Konrads Hold', redText: 'That happens all the time.', ability: 'Shots explode on impact', elements: 'N'},
        {name: 'Lyuda', tier: 2, type: 'Sniper', dedicated: 'Zer0 Mail,Tremendous Rex', location: ',Promethea (Meridian Metroplex)', area: ',Cistern of Slaughter', quest: 'Target of Opportunity 100%,', redText: 'Man killer.', ability: 'Splits into 3 projectiles', elements: 'Any'},
        {name: 'Storm', tier: 2, type: 'Sniper', dedicated: 'Katagawa Jr.', location: 'Promethea', area: 'Atlas HQ', redText: 'Tut, Tut, it looks like rain.', ability: 'Shock orb on impact. 2 ammo/shot. High splash radius', elements: 'S'},
        {name: 'Tankmans Shield', tier: 2, type: 'Sniper', m4: true, dedicated: 'Captain Traunt,Valkyrie Squad / Wotan', location: 'Athenas,', area: 'Athenas,Midnights Cairn', redText: 'You ever seen this dude tank anything ever?', ability: 'Every Kill adds damage to the next magazine', elements: 'Any'},
        {name: 'Woodblocker', tier: 2, type: 'Sniper', dedicated: 'Indo Tyrant', location: 'Eden-6 Basin', redText: 'You dont get into woodblocks unless you are ready to f***.', ability: '4-round burst', elements: 'F C S R O'},
        {name: 'EMP', tier: 2, type: 'Grenade', dedicated: 'Barron Noggin', location: 'Promethea', area: 'Meridian Metroplex', redText: 'Drop the shields.', ability: 'Depletes enemy shields', elements: 'S'},
        {name: 'Epicenter', tier: 2, type: 'Grenade', dedicated: 'DJ Deadsk4g', location: 'Pandora', area: 'The Splinterlands', redText: 'It burns, burns, burns', ability: 'Explodes twice releasing radial of projectiles. ', elements: 'N F'},
        {name: 'Hunter-Seeker', tier: 2, type: 'Grenade', dedicated: 'GenIVIV', location: 'Eden-6', area: 'Voracious Canopy', redText: 'Grip tightly.', ability: 'Splits into 2 slow drones that shoot before exploding', elements: 'Any'},
        {name: 'Firestorm', tier: 2, type: 'Grenade', dedicated: 'Captain Traunt', location: 'Athenas', area: 'Athenas', redText: 'Soon afterwards, the cloud descended upon the earth.', ability: 'Rains fireballs down from the sky', elements: 'F'},
        {name: 'Surge', tier: 2, type: 'Grenade', dedicated: 'Power Troopers', location: 'Promethea', area: 'Atlas HQ', redText: 'Thar she blows!', ability: 'Rubberized. Releases 3 mirv grenades every bounce', elements: 'Any'},
        {name: 'Front Loader', tier: 2, type: 'Shield', dedicated: 'Private Beans', location: 'Athenas', area: 'Athenas', redText: 'You could always use a little more life insurance.', ability: 'Reserves 60% max hp returned as shield capacity', elements: 'N C R O'},
        {name: 'Re-Charger', tier: 2, type: 'Shield', dedicated: 'Urist McEnforcer', location: 'Promethea', area: 'Lectra City', redText: 'Once more, with feeling.', ability: 'Instant recharging with cooldown. Absorbs ammo. Fortify drop chance', elements: 'Any'},
        {name: 'Red Suit', tier: 2, type: 'Shield', dedicated: 'Atomic', location: 'Nekrotafeyo', area: 'Tazendeer Ruins', redText: 'Warning. Containment failure.', ability: '100% Radiation resistance. Nearby enemies take constant rad dmg', elements: 'R'},
        {name: 'Version 0.m', tier: 2, type: 'Shield', dedicated: 'Valkyrie Squad / Wotan', area: 'Midnights Cairn', redText: 'Stand and Clap.', ability: 'Amp: ~125% bonus dmg. Spawns buff circle on shield break for 5 sec', elements: 'Any'},
        {name: 'Re-Charge Berner', tier: 2, type: 'Shield', dedicated: 'Valkyrie Squad', area: 'Midnights Cairn', redText: 'Feelin the Bern.', ability: '16730 dmg on break & fill. Instant recharge when broken 20s cooldown', elements: ' F C R'},
        {name: 'Back Ham', tier: 2, type: 'Shield', dedicated: 'Troy Calypso', location: 'Pandora', area: 'The Great Vault', redText: 'Synthetic Vercuvian ham. Typhon DeLeon approved.', ability: 'Damage taken from behind is reduced by 56%', elements: 'N'},
        {name: 'Cosmic Crater', tier: 2, type: 'Artifact', dedicated: 'General Traunt', location: 'Nekrotafeyo', area: 'Desolations Edge', redText: 'Come on and SLAM!', ability: 'Slam creates a random elemental puddle that lasts for 5 seconds', elements: 'Any'},
        {name: 'Deathless', tier: 2, type: 'Artifact', dedicated: 'Phoenix', location: 'Pandora', area: 'The Splinterlands', redText: 'What do we say to the God of Death?', ability: 'Reserves all but 1 HP. +100% shield cap. +25% r rate. -20% r delay', elements: 'Any'},
        {name: 'Launch Pad', tier: 2, type: 'Artifact', dedicated: 'Red Rain', quest: 'From a quest in Desolations Edge (Nekrotafeyo)', location: 'Slaughterstar 3000', redText: 'Pocket Rockets.', ability: 'Slam Launches a barrage of homing rockets', elements: 'Any'},
        {name: 'Bloodletter', tier: 2, type: 'Class Mod', character: 'Moze', dedicated: 'Skag of Survival', location: 'Gradient of Dawn', quest: 'Trial of Survival', redText: 'Ideas are bulletproof.', ability: 'If Moze is healed, she gains shields instead'},
        {name: 'DE4DEYE', tier: 2, type: 'Class Mod', character: 'Fl4k', dedicated: 'Tink of Cunning', location: 'Ghostlight Beacon', quest: 'Trial of Cunning', redText: 'Cut them down to size.', ability: 'FL4K & their pets deal +35% dmg against enemies above 75% HP'},
        {name: 'Executor', tier: 2, type: 'Class Mod', character: 'Zane', dedicated: 'Skag of Survival', location: 'Gradient of Dawn', quest: 'Trial of Survival', redText: 'Have a plan to kill everyone you meet.', ability: 'Kill skill: On kill +Accuracy, Handling, Crit, Status Effect dmg & chance'},
        {name: 'Phasezerker', tier: 2, type: 'Class Mod', character: 'Amara', dedicated: 'Hag of Fervor', location: 'Skydrowned Pulpit', quest: 'Trial of Fervor', redText: 'I\'m always angry.', ability: 'On AS, gain max Rush stacks, but decay over time. +3%dmg & +10% cooldown/stack'},
        {name: 'Red Fang', tier: 2, type: 'Class Mod', character: 'Fl4k', dedicated: 'Tyrant of Instinct', location: 'Wayward Tether', quest: 'Trial of Instinct', redText: 'Mean and green.', ability: 'While Gamma Burst is active, FL4Ks pet taunts all enemies'},
        {name: 'R4kk P4k', tier: 2, type: 'Class Mod', character: 'Fl4k', m4: true, dedicated: 'Tink of Cunning,Wotan the Invincible', location: 'Ghostlight Beacon,Midnights Cairn', quest: 'Trial of Cunning,', redText: 'Hail and well met!', ability: 'Whenever Fl4ks Rakk hits an enemy, they split into two more Rakk'},
        {name: 'St4ckbot', tier: 2, type: 'Class Mod', character: 'Fl4k', dedicated: 'Jackpot', location: 'The Handsome Jackpot', area: 'VIP Tower', redText: 'If you can make God bleed, people will cease to believe in them.', ability: 'On critical hit, gain +5% wpn dmg until miss on crit. Effect stacks'},
        {name: 'Cosmic Stalker', tier: 2, type: 'Class Mod', character: 'Fl4k', dedicated: 'Tyrant of Instinct', location: 'Wayward Tether', quest: 'Trial of Instinct', redText: 'Like a bird from the snare of the fowler...', ability: 'FL4Ks Hunt Skill Power is increased by 25%'},

        {name: 'Butcher', tier: 3, type: 'Shotgun', dedicated: 'Loot-o-Gram,Raging Titan', location: 'Promethea', area: 'Skywell-27,The Slaughter Shaft', redText: 'Fresh Meat!', ability: 'Fully automatic. Very high fire rate & accuracy', elements: 'Any'},
        {name: 'Face Puncher', tier: 3, type: 'Shotgun', dedicated: 'Handsome Jackie', location: 'Promethea', area: 'Skywell-27', redText: 'Man your own jackhammer.', ability: 'Shoots your melee dmg', elements: 'N'},
        {name: 'Flakker', tier: 3, type: 'Shotgun', dedicated: 'Manvark', location: 'Pandora', area: 'Konrads Hold', redText: 'Flak the world.', ability: 'Explosions everywhere. 5 ammo/shot', elements: 'N F R'},
        {name: 'Hellwalker', tier: 3, type: 'Shotgun', dedicated: 'Road Dog', location: 'Pandora', area: 'The Splinterlands', redText: 'So, my demons. Your time has come.', ability: 'Guitar riff on pickup & every shot. Star shaped spread. Quick reload', elements: 'F'},
        {name: 'Kill-O-The-Wisp', tier: 3, type: 'Shotgun', dedicated: 'Katagawa Ball', location: 'Promethea', area: 'Skywell-27', redText: 'Some say it can lead you to your fate.', ability: 'Charge up to shoot a large slow shock orb. 4 ammo/shot', elements: 'S'},
        {name: 'Redline', tier: 3, type: 'Shotgun', dedicated: 'Road Dog', location: 'Pandora', area: 'The Splinterlands', redText: 'I live my life a quarter mag at a time.', ability: 'Stuck gyrojets increase dmg by 5% each. 2 ammo/shot', elements: 'Any'},
        {name: 'Trevonator', tier: 3, type: 'Shotgun', dedicated: 'Private Beans', location: 'Athenas', area: 'Athenas', redText: 'Trev is gunna get you!', ability: 'Very low charge time. 3-round burst', elements: 'Any'},
        {name: 'Faisor', tier: 3, type: 'AR', dedicated: 'Atomic', location: 'Nekrotafeyo', area: 'Tazendeer Ruins', redText: 'Set Faisors to kill.', ability: 'Full auto / Shotgun', elements: 'Any'},
        {name: 'Juliets Dazzle', tier: 3, type: 'AR', m4: true, dedicated: 'Aurelia Hammerlock,Valkyrie Squad / Wotan', location: 'Eden-6,', area: 'Blackbarrel Cellars,Midnights Cairn', redText: 'Lights up the world', ability: 'Killing an enemy automatically refills the magazine.', elements: 'N O'},
        {name: 'Laser Sploder', tier: 3, type: 'AR', dedicated: 'Sylestro', location: 'Nekrotafeyo', area: 'Tazendeer Ruins', redText: 'LASERS ≠ EXPLOSIONS!?', ability: 'Constant laser of elemental damage and rockets', elements: 'F C S R O'},
        {name: 'Lucians Call', tier: 3, type: 'AR', dedicated: 'Loot-o-Gram,Blue Fire', location: 'Promethea,Slaughterstar 3000', area: 'Skywell-27,', quest: ',From a quest in Desolations Edge (Nekrotafeyo)', redText: 'What happened?', ability: 'Crit returns 2 bullets to mag & ricochets 2 bullets', elements: 'F C O'},
        {name: 'Ogre', tier: 3, type: 'AR', dedicated: 'Anointed Alpha', location: 'Eden-6', area: 'The anvil', redText: 'Its all ogre now.', ability: 'Shots explode on impact. High magazine size', elements: 'N'},
        {name: 'Rowans Call', tier: 3, type: 'AR', dedicated: 'Red Rain', quest: 'From a quest in Desolations Edge (Nekrotafeyo)', location: 'Slaughterstar 3000', redText: 'Uh-oh!', ability: 'Crit ricochets 2 bullets & returns 2 bullets to mag. Lasers', elements: 'F S R'},
        {name: 'Shredifier', tier: 3, type: 'AR', dedicated: 'Raging Titan', location: 'Pandora (Konrads Hold)', area: 'The Slaughter Shaft', redText: 'Speed Kills.', ability: 'Full-Auto / Random underbarrel attachment. High fire rate & mag size', elements: 'Any'},
        {name: 'Seeryul Killer', tier: 3, type: 'AR', dedicated: 'World Drop Only', location: 'DLC 2', area: '', redText: 'Look at that unsubtle blood-red coloring...', ability: 'Kill grants increased dmg, fire rate & reduces heat. Stacks 3 times', elements: 'F'},
        {name: 'Zheitsevs Eruption', tier: 3, type: 'AR', m4: true, dedicated: 'Valkyrie Squad / Wotan,Raging Titan', location: ',Pandora (Konrads Hold)', area: 'Midnights Cairn,Slaughter Shaft', redText: 'Pain and Misery erupt in the Void.', ability: 'Launches homing projectiles when overheating', elements: 'N F C O'},
        {name: 'Polyaimorous', tier: 3, type: 'SMG', dedicated: '50 Hearts', location: 'Broken Hearts Event', redText: 'Spread the love.', ability: 'Shoots a continuous beam. Chains to nearby enemies', elements: 'F S'},
        {name: 'Crossroad', tier: 3, type: 'SMG', dedicated: 'Katagawa Jr.', location: 'Promethea', area: 'Atlas HQ', redText: 'Open the gate for me.', ability: '6-round burst. 2 ammo/shot', elements: 'F C S R O'},
        {name: 'Devoted', tier: 3, type: 'SMG', dedicated: 'Captain Traunt', location: 'Athenas', area: 'Athenas', redText: 'This is your champion.', ability: 'Increases fire rate the longer you shoot. High mag size', elements: 'Any'},
        {name: 'Tsunami', tier: 3, type: 'SMG', dedicated: 'Katagawa Ball', location: 'Promethea', area: 'Skywell-27', redText: 'You cant explain that.', ability: 'Fires in alternating diagonal rows of corrosive & shock', elements: 'C S'},
        {name: 'Westergun', tier: 3, type: 'SMG', dedicated: 'Private Beans', location: 'Athenas', area: 'Athenas', redText: 'I believe ya, but my tommy gun dont.', ability: ' +75 splash radius', elements: 'Any'},
        {name: 'AAA', tier: 3, type: 'Pistol', dedicated: 'Wick and Warty', location: 'Promethea', area: 'Lectra City', redText: 'Hold on! They\'re lithium!', ability: 'Burst fire. Projectiles form an "A" pattern. High elemental chance', elements: 'N S'},
        {name: 'Devastator', tier: 3, type: 'Pistol', dedicated: 'Unstoppable', location: 'Eden-6', area: 'Ambermire', redText: 'Hail.', ability: '2-round burst. +292 splash radius', elements: 'N'},
        {name: 'Duc', tier: 3, type: 'Pistol', dedicated: 'The Rampager', location: 'Promethea', area: 'Forgotten Basilica', redText: 'Fire that off to me real quick.', ability: 'Sticky explosive rounds. Crit ricochets 2 bullets to nearest enemy', elements: 'N'},
        {name: 'Hydrafrost', tier: 3, type: 'Pistol', dedicated: 'Shiverous the Unscathed', location: 'Xylourgos', area: 'Negul Neshai', redText: 'Tell your heads to chill.', ability: 'After a kill, every 2nd shot deals 200% shock or incendiary dmg for 6 sec', elements: 'O'},
        {name: 'Little Yeeti', tier: 3, type: 'Pistol', dedicated: 'Yeti', location: 'Xylourgos', area: 'Skittermaw Basin', redText: 'Yeet em if you got em!', ability: 'Multiple projectiles. Chance to knockback enemies', elements: 'N'},
        {name: 'Kings Call', tier: 3, type: 'Pistol', dedicated: 'Tyreen the Destroyer', location: 'Pandora', area: 'Destroyers Rift', redText: 'Life is ours, we live it our way.', ability: 'Crit ricochets 3 bullets & returns 3 bullets to mag', elements: 'F S C R O'},
        {name: 'Linoge', tier: 3, type: 'Pistol', dedicated: 'Lavender Crawly', location: 'Pandora', area: 'The Droughts', redText: 'My name is legion, for we are many', ability: 'Hail of slow ricocheting bullets. 4 ammo/shot', elements: 'F C'},
        {name: 'Nemesis', tier: 3, type: 'Pistol', dedicated: 'Mouthpiece', location: 'Pandora', area: 'Ascension Bluff', redText: 'A righteous infliction of retribution.', ability: 'Semi-Auto / 3-round burst. Deals additional shock dmg', elements: 'F C'},
        {name: 'Queens Call', tier: 3, type: 'Pistol', dedicated: 'Tyreen the Destroyer', location: 'Pandora', area: 'Destroyers Rift', redText: 'Life is ours, we live it our way.', ability: 'Crit ricochets 3 bullets & returns 3 bullets to mag', elements: 'F S C R O'},
        {name: 'Roisens Thorns', tier: 3, type: 'Pistol', dedicated: 'Princess Tarantella II', location: 'Pandora', area: 'The Splinterlands', redText: 'Where there is pleasure, there is pain.', ability: 'Impact shoots 4 fire rockets and 1 corrosive. Sticky is only corrosive', elements: 'C'},
        {name: 'Skeksil', tier: 3, type: 'Pistol', dedicated: 'Skrakk', location: 'Pandora', area: 'Ascension Bluff', redText: 'Get back, splithead!', ability: 'Occasionally sends out 2 rockets', elements: 'F S C'},
        {name: 'Nukem', tier: 3, type: 'Rocket Launcher', dedicated: 'Loco Chantelle', location: 'The Handsome Jackpot', area: 'VIP Tower', redText: 'Name dropper.', ability: 'Mortar rockets with large splash radius', elements: 'N'},
        {name: 'Rubys Wrath', tier: 3, type: 'Rocket Launcher', dedicated: 'Chonk Stomp', location: 'Eden-6', area: 'Floodmoor Basin', redText: 'No one can escape.', ability: '7 rockets that can be homed in using alternative fire: vortex grenade', elements: 'N'},
        {name: 'Tunguska', tier: 3, type: 'Rocket Launcher', dedicated: 'Chonk Stomp', location: 'Eden-6', area: 'Floodmoor Basin', redText: 'Crack the skye.', ability: 'Fires 2 rockets that rise on impact before detonating', elements: 'N'},
        {name: 'Monocle', tier: 3, type: 'Sniper', dedicated: 'Demoskaggons', location: 'Pandora', area: 'The Droughts', redText: 'One is enough.', ability: 'High +crit dmg bonus while ADS ~500%. High accuracy. High Zoom', elements: 'N'},
        {name: 'Tinas Hippity Hopper', tier: 3, type: 'Grenade', dedicated: 'Raging Titan', location: 'Pandora (Konrads Hold)', area: 'The Slaughter Shaft', redText: 'Hare today, bomb tomorrow.', ability: 'Rubberized. Releases 2 mirv grenades every bounce', elements: 'Any'},
        {name: 'Tran-fusion', tier: 3, type: 'Grenade', dedicated: 'Power Troopers', location: 'Promethea', area: 'Atlas HQ', redText: 'Here go, hell come.', ability: 'Heals for 120% of hp dmg dealt. Heals shields for 30% shield dmg', elements: 'Any'},
        {name: 'Widow Maker', tier: 3, type: 'Grenade', dedicated: 'Aurelia Hammerlock', location: 'Eden-6', area: 'Blackbarrel Cellars', redText: 'À la vie, à la mort.', ability: 'Proximity grenade. Spawns homing rockets', elements: 'Any'},
        {name: 'Frozen Heart', tier: 3, type: 'Shield', dedicated: 'Aurelia Hammerlock', location: 'Eden-6', area: 'Blackbarrel Cellars', redText: 'I feel... cold.', ability: 'Nova 30% of nova dmg returned as HP', elements: 'O'},
        {name: 'Frozen Snowshoe', tier: 3, type: 'Shield', dedicated: 'Valkyrie Squad', area: 'Midnights Cairn', redText: 'Give em the cold toelder.', ability: 'Sliding into enemies drains all shields & deals up to 5949 bonus cryo', elements: 'O'},
        {name: 'Messy Breakup', tier: 3, type: 'Shield', dedicated: 'GenIVIV', location: 'Eden-6', area: 'Voracious Canopy', redText: 'Its complicated.', ability: 'Gives you a drone. Drone dmg is same as element resist', elements: 'N C S'},
        {name: 'Ward', tier: 3, type: 'Shield', dedicated: 'Graveward', location: 'Eden-6', area: 'The Floating Tomb', redText: 'Free me master, see me shiver', ability: ' +25% weapon dmg, +300% melee dmg depleted. +2%hp/sec active', elements: 'Any'},
        {name: 'Electric Banjo', tier: 3, type: 'Artifact', dedicated: 'Psychobillies', location: 'Eden-6', area: 'Ambermire', redText: 'We never could have foreseen the success.', ability: '20% bullet proc chance to chain electric'},
        {name: 'Loaded Dice', tier: 3, type: 'Artifact', dedicated: 'Pain', location: 'Pandora', area: 'Guts of Carnivora', redText: 'Feelin\' Lucky?', ability: '-75% Max HP. Increases Luck', elements: 'Any'},
        {name: 'Safeguard', tier: 3, type: 'Artifact', dedicated: 'Rakkman', location: 'Pandora', area: 'Carnivora', redText: 'My own little bubble.', ability: 'Slam triggers a shield that reduces dmg taken by +57%. Lasts 5 sec', elements: 'Any'},
        {name: 'White Elephant', tier: 3, type: 'Artifact', dedicated: 'Agonizer 9000 & Terror', location: 'Pandora', area: 'Guts of Carnivora', redText: 'Its a SURPRISE!', ability: 'Melee attacks have a 30% chance to attach a sticky bomb of a random element'},
        {name: 'Antifreeze', tier: 3, type: 'Class Mod', character: '', m4: true, dedicated: 'Arbalest of Discipline,Wotan the Invincible', location: 'Precipice Anchor,Midnights Cairn', quest: 'Trial of Discipline,', redText: 'Jet propulsion disengage.', ability: 'While sliding or airborne, gain +40% wpn dmg and +20% dmg reduction'},
        {name: 'Friend-Bot', tier: 3, type: 'Class Mod', character: 'Fl4k', dedicated: 'Arbalest of Discipline', location: 'Precipice Anchor', quest: 'Trial of Discipline', redText: 'Dont worry, the dog lives.', ability: 'On enemy kill pet gains Second Wind. Pet dmg +20%'},
        {name: 'Green Monster', tier: 3, type: 'Class Mod', character: 'Moze', dedicated: 'Jackpot', location: 'The Handsome Jackpot', area: 'VIP Tower', redText: 'We often smilin\' at sights of violence.', ability: 'Bonus corrosive dmg to weapons after firing for a few seconds'},
        {name: 'Infiltrator', tier: 3, type: 'Class Mod', character: 'Zane', dedicated: 'Tyrant of Instinct', location: 'Wayward Tether', quest: 'Trial of Instinct', redText: 'When the leaves hang trembling, the wind is passing through.', ability: 'Weapon dmg & shield increase ~20%. Higher bonus with low shield'},
        {name: 'Mind Sweeper', tier: 3, type: 'Class Mod', character: 'Moze', dedicated: 'Tink of Cunning', location: 'Ghostlight Beacon', quest: 'Trial of Cunning', redText: 'Brain blast!', ability: 'Crit hit has 25% chance to drop Micro grenade that explodes'},
        {name: 'Nimbus', tier: 3, type: 'Class Mod', character: 'Amara', dedicated: 'Sera of Supremacy', location: 'Hall Obsidian', quest: 'Trial of Supremacy', redText: 'Its a terrible day for rain.', ability: 'First dmg from Action Skill creates cloud of Action Skill Element'},
        {name: 'Raging Bear', tier: 3, type: 'Class Mod', character: 'Moze', m4: true, dedicated: 'Billy The Annointed,Wotan the Invincible', location: 'Eden-6,Midnights Cairn', area: 'Jakobs Estate,', redText: 'You won\'t just be strong. You\'ll be unbeatable.', ability: 'IB kills decreases Fuel Usage. IB takes damage, +IB dmg'},

        {name: 'Boring Gun', tier: 4, type: 'Shotgun', dedicated: 'Antalope', location: 'Pandora', area: 'Devils Razor', redText: 'This is beyond science.', ability: 'Shoots 3 grounded sawblades that dig in fired direction. 2 ammo/shot', elements: 'Any'},
        {name: 'Deathgrip', tier: 4, type: 'Shotgun', m4: true, dedicated: 'Troy Calypso,Valkyrie Squad / Wotan', location: 'Pandora,', area: 'The Great Vault,Midnights Cairn', redText: 'A good death is its own reward.', ability: '"Vosks Grasp", a singularity shot / 6 shot laser trap', elements: 'F C S R O'},
        {name: 'Fearmonger', tier: 4, type: 'Shotgun', dedicated: 'Loot Ghost', location: 'Bloody Harvest Event', area: 'The Heck Hole', redText: 'I cant control their fear, only my own.', ability: 'Increased pellets per terror level up to 7', elements: 'F C S R O'},
        {name: 'Flama Diddle', tier: 4, type: 'Shotgun', dedicated: 'World Drop Only', location: 'DLC 2', area: '', redText: 'VIII. Never turn your back on the Monster!', ability: 'Reload shoots twice before exploding on impact. Bullets ricochet once', elements: 'F'},
        {name: 'Heart Breaker', tier: 4, type: 'Shotgun', dedicated: 'Georgous Armada', location: 'The Handsome Jackpot', area: 'The Compactor', redText: 'I dont want to set the world on fire...', ability: 'Heals you when damaging enemy. Heart shaped projectile pattern', elements: 'F C S O'},
        {name: 'Horizon', tier: 4, type: 'Shotgun', dedicated: 'Maxitrillion', location: 'Eden-6', area: 'Voracious Canopy', redText: 'You cant leave. She wont let you.', ability: 'Reload projects target that can be shot to create a Singularity', elements: 'Any'},
        {name: 'Phebert', tier: 4, type: 'Shotgun', dedicated: 'Wick and Warty', location: 'Promethea', area: 'Lectra City', redText: 'Faster than all estimates.', ability: '2 ammo/shot', elements: 'Any'},
        {name: 'Slow Hand', tier: 4, type: 'Shotgun', dedicated: 'DEGEN-3', location: 'The Handsome Jackpot', area: 'Impound Deluxe', redText: 'Take your time, sugar...', ability: 'Heals you when damaging enemy. Slow explosive projectiles', elements: 'F C S R O'},
        {name: 'Tidal Wave', tier: 4, type: 'Shotgun', dedicated: 'Dumptruck', location: 'Pandora', area: 'The Droughts', redText: 'Flee the wave, dude!', ability: 'Projectiles travel in a tidal wave pattern. Ricochets off surfaces. ', elements: 'N'},
        {name: 'Barrage', tier: 4, type: 'AR', dedicated: 'Skrakk', location: 'Pandora', area: 'Ascension Bluff', redText: 'Quick maths.', ability: '3-round burst', elements: 'N C R'},
        {name: 'Embrace the Pain', tier: 4, type: 'AR', dedicated: 'Hot Karl', location: 'Pandora', area: 'Devils Razor', redText: 'It hurts, HAHAHAHAHA! IT HURTS!!', ability: 'Chance to light yourself on fire', elements: 'F'},
        {name: 'Gatling Gun', tier: 4, type: 'AR', dedicated: 'Billy, The Anointed', location: 'Eden-6', area: 'Jakobs Estate', redText: 'Watch me crank it, watch me roll.', ability: 'Fully-Auto. Increases fire rate the longer you shoot. +Crit% bonus', elements: 'N'},
        {name: 'Lead Sprinkler', tier: 4, type: 'AR', dedicated: 'Billy The Anointed,Jabbermogwai', location: 'Eden-6,Eden-6', area: 'Jakobs Estate,Voracious Canopy', redText: 'Splish splash.', ability: 'Crit spawns explosive projectile. Ricochets off enemy', elements: 'N'},
        {name: 'More Pain Is Power', tier: 4, type: 'AR', dedicated: 'Hot Karl', location: 'Pandora', area: 'Devils Razor', redText: 'Nobody kills me but ME!', ability: 'Damages player when fired. Light yourself on fire when overheated', elements: 'F'},
        {name: 'Mutant', tier: 4, type: 'AR', dedicated: 'Fungal Gorger', location: 'Xylourgos', area: 'The Cankerwood', redText: 'Super unnatural.', ability: 'Full-Auto laser', elements: 'N'},
        {name: 'Try-Bolt', tier: 4, type: 'AR', dedicated: 'Manvark', location: 'Pandora', area: 'Konrads Hold', redText: 'Do... or do not-bolt.', ability: '3 round grenade launcher', elements: 'N F C S R'},
        {name: 'Warlord', tier: 4, type: 'AR', dedicated: 'Billy, The Anointed', location: 'Eden-6', area: 'Jakobs Estate', redText: 'My gun sings for your blood.', ability: '30% chance to not consume ammo. High fire rate & mag size', elements: 'N F C S'},
        {name: 'Bitch', tier: 4, type: 'SMG', dedicated: 'Tyreen the Destroyer', location: 'Pandora', area: 'Destroyers Rift', redText: 'If you cant handle me at my worst...', ability: 'High accuracy and fire rate', elements: 'Any'},
        {name: 'Cheap Tips', tier: 4, type: 'SMG', dedicated: 'Jackpot', location: 'The Handsome Jackpot', area: 'VIP Tower', redText: 'I\'ll get home early from work.', ability: 'Dmging enemies, 10% chance to drop chips that +10% wpn dmg for 12s', elements: 'Any'},
        {name: 'Cloud Kill', tier: 4, type: 'SMG', dedicated: 'Quest Reward', quest: 'Beneath the Meridian (Talk to Ava)', location: 'Promethea', area: 'Forgotten Basilica', redText: 'Now, you will rise.', ability: 'Produces a green cloud. High fire rate', elements: 'C'},
        {name: 'Destructo Spinner', tier: 4, type: 'SMG', dedicated: 'Power Troopers', location: 'Promethea', area: 'Atlas HQ', redText: 'Ive been hired for destruction.', ability: 'Projectiles spin', elements: 'Any'},
        {name: 'Handsome Jackhammer', tier: 4, type: 'SMG', dedicated: 'Handsome Jackie', location: 'Promethea', area: 'Skywell-27', redText: 'Everyone thinks they are the heroes of their own stories.', ability: 'Reload bounces releasing novas & shooting. HJ voice randomly plays', elements: 'Any'},
        {name: 'Hellfire', tier: 4, type: 'SMG', dedicated: 'Jabermogwai (Must kill with fire)', location: 'Eden-6', area: 'Voracious Canopy', redText: 'We dont need no... something...', ability: 'Full-Auto. High elemental damage & fire rate. Variable zoom', elements: 'F'},
        {name: 'SF Force', tier: 4, type: 'SMG', dedicated: 'DJ Spinsmouth', location: 'Xylourgos', area: 'Skittermaw Basin', redText: 'Flavor-blast them all.', ability: 'Shoots musical notes of both elements', elements: 'F C S R O'},
        {name: 'Smart Gun', tier: 4, type: 'SMG', dedicated: 'Gigamind', location: 'Promethea', area: 'Meridian Metroplex', redText: 'Busy getting brain like Krang.', ability: 'Reload becomes a sticky turret ', elements: 'C'},
        {name: '9-Volt', tier: 4, type: 'Pistol', dedicated: 'Killavolt', location: 'Promethea', area: 'Lectra City', redText: 'Contact.', ability: 'Burst-fire. Shoots triangle of shock projectiles and a lot of sparks', elements: 'S'},
        {name: 'Baby Maker', tier: 4, type: 'Pistol', dedicated: 'Brood Mother,Alacritous Vanda,CL4P-TP Mail', location: 'Nekrotafeyo', area: 'The Pyre of Stars,Cistern of Slaughter,', quest: ',,Dead Claptrap 100%', redText: 'Safety off.', ability: 'Reload explodes on impact and becomes 4 flying pistols', elements: 'Any'},
        {name: 'Companion', tier: 4, type: 'Pistol', dedicated: 'Hot Karl', location: 'Pandora', area: 'Devils Razor', redText: 'You cant take the sky from me.', ability: 'Crit ignites enemy. Very High elemental dmg', elements: 'F'},
        {name: 'Devils Foursum', tier: 4, type: 'Pistol', dedicated: 'Psychobillies', location: 'Eden-6', area: 'Ambermire', redText: 'I love it when a plan comes together.', ability: '3 explosive shots that come together at a single point', elements: 'Any'},
        {name: 'Hornet', tier: 4, type: 'Pistol', dedicated: 'Chupacabratch', location: 'Athenas', area: 'Athenas', redText: 'Fear the Swarm!', ability: '6-round burst. High elemental dmg & splash radius', elements: 'C'},
        {name: 'Linc', tier: 4, type: 'Pistol', dedicated: 'Anointed Alpha', location: 'Eden-6', area: 'The Anvil', redText: 'Power is pizza.', ability: 'Fast fire rate & bullet speed', elements: 'N'},
        {name: 'Pestilence', tier: 4, type: 'Pistol', dedicated: 'Heckle/Hyde,Sylestro', location: 'Eden-6,Nekrotafeyo', area: 'Jakobs Estate,Tazendeer Ruins', redText: 'Go forth conquering, and to conquer.', ability: 'Releases radiation explosion when broken. High fire rate', elements: 'R'},
        {name: 'Sellout', tier: 4, type: 'Pistol', dedicated: 'Quest Reward', quest: 'Sell Out (Suicide option)', location: 'Eden-6', area: 'Ambermire', redText: 'Hey there, superfan!', ability: 'Quick laser that explodes as an orb on impact. Damages user', elements: 'F C'},
        {name: 'Thunderball Fist', tier: 4, type: 'Pistol', dedicated: 'Power Troopers', location: 'Promethea', area: 'Atlas HQ', redText: 'I can have such a thing?', ability: 'Shock orb. 2 ammo/shot', elements: 'S'},
        {name: 'Unforgiven', tier: 4, type: 'Pistol', dedicated: 'Indo Tyrant', location: 'Eden-6', area: 'Floodmoor Basin', redText: 'Its a helluva thing...', ability: ' +432% crit dmg. Unique reload animation', elements: 'N'},
        {name: 'BackBurner', tier: 4, type: 'Rocket Launcher', m6: true, dedicated: 'Agonizer 9000', location: 'Pandora', area: 'Guts of Carnivora', redText: 'We\'ll get to it eventually.', ability: 'Lob-style orbs with singularity. Spawns non-singularity mirv orbs. 3 ammo/shot', elements: 'Any'},
        {name: 'Freeman', tier: 4, type: 'Rocket Launcher', dedicated: 'Warden', location: 'Eden-6', area: 'The Anvil', redText: 'The right man in the wrong place can make all the difference in the world.', ability: 'Laser guide your missiles', elements: 'N'},
        {name: 'Hive', tier: 4, type: 'Rocket Launcher', dedicated: 'Princess Tarantella II', location: 'Pandora', area: 'The Splinterlands', redText: 'Full of bees.', ability: 'Launches hovering ball that shoots many rockets before exploding', elements: 'C R'},
        {name: 'Malaks Bane', tier: 4, type: 'Sniper', dedicated: 'Pheonix', location: 'Pandora', area: 'The Splinterlands', redText: 'Welcome to the end.', ability: 'Semi-Auto ricochet, 2 ammo/shot / Shotgun fireballs, 5 ammo/shot', elements: 'F O'},
        {name: 'Mind Killer', tier: 4, type: 'Sniper', dedicated: 'Mouthpiece', location: 'Pandora', area: 'Ascension Bluff', redText: 'I must not fear. Fear is the mind-killer', ability: 'Can charge up shot.', elements: 'N'},
        {name: 'Chupa\'s Organ', tier: 4, type: 'Grenade', dedicated: 'Chupacabratch', location: 'Athenas', area: 'Athenas', redText: 'Cabrón.', ability: 'Sticks to enemy and does damage over time to health. Ignores shields', elements: 'N'},
        {name: 'Nagata', tier: 4, type: 'Grenade', dedicated: 'Chupacabratch', location: 'Athenas', area: 'Athenas', redText: 'Beltalowda!', ability: 'Spawns circle of longbow grenades', elements: 'N'},
        {name: 'Black Hole', tier: 4, type: 'Shield', dedicated: 'Wick and Warty', location: 'Promethea', area: 'Lectra City', redText: 'Shes gone from suck to blow.', ability: 'Nova & Black Hole (Pulls enemies in)', elements: 'N S'},
        {name: 'Impaler', tier: 4, type: 'Shield', dedicated: 'Antalope', location: 'Pandora', area: 'Devils Razor', redText: 'Out for a walk, bitch.', ability: 'Spike. Fires homing spikes to attackers when taking bullet dmg', elements: 'C'},
        {name: 'Nova Berner', tier: 4, type: 'Shield', dedicated: 'Power Troopers', location: 'Promethea', area: 'Atlas HQ', redText: 'Feel the Bern.', ability: 'Nova on depletion and fill', elements: 'F'},
        {name: 'Rough Rider', tier: 4, type: 'Shield', dedicated: 'Urist McEnforcer', location: 'Promethea', area: 'Lectra City', redText: 'It takes more than that to kill a Bull Moose.', ability: 'No capacity. Reduces incoming dmg by 23% & grants +35% Max HP', elements: 'Any'},
        {name: 'Shooting Star', tier: 4, type: 'Shield', dedicated: 'Sky Bully', location: 'Eden-6', area: 'The Anvil', redText: 'Dont look up.', ability: 'While depleted, successful melee summons a projectile', elements: 'Any'},
        {name: 'Commander Planetoid', tier: 4, type: 'Artifact', dedicated: 'Atomic', location: 'Nekrotafeyo', area: 'Tazendeer Ruins', redText: 'The power is YOURS!', ability: '+72% elemental melee damage. Element type changes every 5 sec', elements: 'Any'},
        {name: 'Grave', tier: 4, type: 'Artifact', dedicated: 'Graveward', location: 'Eden-6', area: 'The Floating Tomb', redText: 'Pain becomes power.', ability: '+melee < 50% HP. +weapon dmg < 20% HP. +splash dmg < 5% HP'},
        {name: 'Unleash the Dragon', tier: 4, type: 'Artifact', dedicated: 'El Dragon Jr.', location: 'Eden-6', area: 'Jakobs Estate', redText: 'En fuego!', ability: 'Melee, slide, & ground slam have 100% chance to ignite enemy'},
        {name: 'Bear Trooper', tier: 4, type: 'Class Mod', character: 'Moze', dedicated: 'Tyrant of Instinct', location: 'Warward Tether', quest: 'Trial of Instinct', redText: 'Rocket \'til the wheels fall off.', ability: 'Decreases fuel use, increases Iron Bears duration'},
        {name: 'Breaker', tier: 4, type: 'Class Mod', character: 'Amara', dedicated: 'Skag of Survival', location: 'Gradient of Dawn', quest: 'Trial of Survival', redText: 'The closer we are to danger, the further we are from harm.', ability: 'Up to 29% dmg reduction while close to enemy'},
        {name: 'Cold Warrior', tier: 4, type: 'Class Mod', character: 'Zane', dedicated: 'Sera of Supremacy', location: 'Hall Obsidian', quest: 'Trial of Supremacy', redText: 'A song of ice and radiation and acid and lightning and fire', ability: 'Random Status Effect applied to enemies Zane freezes'},
        {name: 'Golden Rule', tier: 4, type: 'Class Mod', character: 'Amara', dedicated: 'Jackpot', location: 'The Handsome Jackpot', area: 'VIP Tower', redText: 'I can do this all day.', ability: 'Increases Action skill cooldown rate [5%] for 8s when taking damage'},

        {name: 'Polybius', tier: 5, type: 'Shotgun', dedicated: 'GenIVIV', location: 'Eden-6', area: 'Voracious Canopy', redText: '21. 11. 33. 14. 24. 42.', ability: 'Reload becomes a crab turret. Spread forms a square', elements: 'F C S R O'},
        {name: 'Sledges Shotgun', tier: 5, type: 'Shotgun', dedicated: 'Hot Karl', location: 'Pandora', area: 'Devils Razor', redText: 'The Legend Lives (still)', ability: 'High mag size. Fires in bursts. 2 ammo/shot', elements: 'N'},
        {name: 'Rebel Yell', tier: 5, type: 'AR', dedicated: 'Sky Bullies', location: 'Eden-6', area: 'The Anvil', redText: 'When you charge, yell like Furies.', ability: 'Regular bullets deal normal dmg. Tracker bullets deal shock dmg', elements: 'N S'},
        {name: 'Boomer', tier: 5, type: 'SMG', dedicated: 'Claptrap Prime', location: 'The Handsome Jackpot', area: 'The Compactor', redText: 'Some like it hot.', ability: 'Full-Auto / 5-round burst. 2 ammo/shot. Explosive shots', elements: 'N F'},
        {name: 'DNA', tier: 5, type: 'SMG', m6: true, dedicated: 'General Traunt', location: 'Nekrotafeyo', area: 'Desolations Edge', redText: 'Death cannot be contained.', ability: 'Shoots random elemental pairs of projectiles. Double helix pattern', elements: 'N'},
        {name: 'Muskett', tier: 5, type: 'SMG', dedicated: 'Lagromar', location: 'Pandora', area: 'Konrads Hold', redText: 'Say "cryptocurrency"!', ability: 'Reload has legs. Flamethrower. Can stick to walls.', elements: 'F'},
        {name: 'Predatory Lending', tier: 5, type: 'SMG', dedicated: 'Lavender Crawley', location: 'Pandora', area: 'The Droughts', redText: 'Bullets are cheap, but not that cheap.', ability: 'Uses cash instead of ammo. $1/shot Low acc. to $3/shot Max acc.', elements: 'N F S R'},
        {name: 'Ripper', tier: 5, type: 'SMG', dedicated: 'Brood Mother,Alicritious Vanda', location: 'Nekrotafeyo,Promethea (Meridian Metroplex)', area: 'The Pyre of Stars,Cistern of Slaughter', redText: 'They say I\'m a doctor now.', ability: 'Bladed. Enemies you melee take increased bullet dmg from ripper', elements: 'Any'},
        {name: 'Vault Hero', tier: 5, type: 'SMG', dedicated: 'VIP Insider Reward', redText: '', ability: '', elements: 'C S'},
        {name: 'Turbo Ten Gallon', tier: 5, type: 'SMG', dedicated: 'GenIVIV', location: 'Eden-6', area: 'Voracious Canopy', redText: 'Let me tell you about my best friend.', ability: 'Reload becomes a drone. Explode on impact', elements: 'Any'},
        {name: 'Amazing Grace', tier: 5, type: 'Pistol', dedicated: 'Quest Reward', quest: 'Line of the Party', location: 'Pandora', area: 'Devils Razor', redText: 'Memento mori.', ability: 'Crit returns bullet to mag. Low fire rate. High dmg', elements: 'N'},
        {name: 'Bangarang', tier: 5, type: 'Pistol', dedicated: 'Thunk & Sloth', location: 'Pandora', area: 'Konrads Hold', redText: 'To die would be a grand adventure.', ability: 'Reload flies around continuously spinning & shooting rapidly', elements: 'Any'},
        {name: 'Breeder', tier: 5, type: 'Pistol', dedicated: 'Psychobillies', location: 'Eden-6', area: 'Ambermire', redText: 'Man hands on misery to man.', ability: 'Shoots sticky that spawns small mirv grenades', elements: 'Any'},
        {name: 'Echo', tier: 5, type: 'Pistol', dedicated: 'Psychobillies', location: 'Eden-6', area: 'Ambermire', redText: 'Dont make me repeat myself.', ability: 'Sticky shot for delayed explosion', elements: 'Any'},
        {name: 'Flood', tier: 5, type: 'Pistol', dedicated: 'Lagromar', location: 'Pandora', area: 'Konrads Hold', redText: 'Take us.', ability: 'Full-Auto. Incredibly fast fire rate', elements: 'N'},
        {name: 'Gunerang', tier: 5, type: 'Pistol', dedicated: 'Indo Tyrant', location: 'Eden-6', area: 'Floodmoor Basin', redText: 'Give it a burl.', ability: 'Reload flies around like a Boomerang', elements: 'N C S R O'},
        {name: 'Infinity', tier: 5, type: 'Pistol', dedicated: 'Anointed Alpha', location: 'Eden-6', area: 'The anvil', redText: 'Its closer than you think! (no it isnt)', ability: 'Infinite Ammo. Full-Auto. Spray pattern resembles infinity symbol', elements: 'Any'},
        {name: 'Magnificent', tier: 5, type: 'Pistol', dedicated: 'Jabbermogwai', location: 'Eden-6', area: 'Voracious Canopy', redText: 'Yedesh na den\', khleba beri na nedelyu.', ability: 'Very low accuracy. High fire rate', elements: 'N F C S'},
        {name: 'Night Flyer', tier: 5, type: 'Pistol', dedicated: 'Rakkman', location: 'Pandora', area: 'Carnivora', redText: 'I have one rule', ability: 'Burst fire. Variable zoom. Dmgs enemy to 1HP', elements: 'N'},
        {name: 'Occultist', tier: 5, type: 'Pistol', dedicated: 'Troy Calypso', location: 'Pandora', area: 'The Great Vault', redText: 'The only way you can control people is to lie to them.', ability: 'Shoots swirling fireballs', elements: 'F'},
        {name: 'Psycho Stabber', tier: 5, type: 'Pistol', dedicated: 'Borman Nates', location: 'Promethea', area: 'Meridian Outskirts', redText: 'Fa fa fa fa, fa fa fa fa fa fa...', ability: ' +125% melee damage', elements: 'N'},
        {name: 'Superball', tier: 5, type: 'Pistol', dedicated: 'Baron Noggin', location: 'Promethea', area: 'Meridian Metroplex', redText: 'Flower power.', ability: 'Shoots small fire balls that bounce along the ground', elements: 'F'},
        {name: 'Creamer', tier: 5, type: 'Rocket Launcher', dedicated: 'Junpai Goat Eater', location: 'The Handsome Jackpot', area: 'VIP Tower', redText: 'Non-dairy.', ability: 'Heals you when damaging enemy. Projectile nova', elements: 'Any'},
        {name: 'Jericho', tier: 5, type: 'Rocket Launcher', dedicated: 'Crushjaw', location: 'Pandora', area: 'Cathedral of the Twin Gods', redText: 'I prefer the weapon you only need to fire once.', ability: 'Launcher / Mortar. Explodes into mirv grenades', elements: 'R'},
        {name: 'Quadomizer', tier: 5, type: 'Rocket Launcher', dedicated: 'The Rampager', location: 'Promethea', area: 'Forgotten Basilica', redText: 'Damn near killed \'em.', ability: 'Shoots 4 Massive Rockets. Alternates elements. 2 ammo/shot', elements: 'FCR'},
        {name: 'AutoAime', tier: 5, type: 'Sniper', dedicated: 'Freddie the Traitor', location: 'The Handsome Jackpot', area: 'VIP Tower', redText: 'OGC HOOKED.', ability: 'Full-Auto / 2-round burst. Shoots homing lasers', elements: 'N F C S'},
        {name: 'Masterwork Crossbow', tier: 5, type: 'Sniper', dedicated: 'Urist McEnforcer', location: 'Promethea', area: 'Lectra City', redText: 'All craftsdwarfship is of the highest quality.', ability: 'Shoots explosive bolt. One shot mag size', elements: 'N'},
        {name: 'Red Queen', tier: 5, type: 'Grenade', dedicated: 'Blinding Banshee', location: 'Nekrotafeyo', area: 'Desolations Edge', redText: 'OFF WITH THEIR HEADS!', ability: 'Rubberized. Splits into 2 laser-connected grenades. ', elements: 'N'},
        {name: 'Moxxis Bouncing Pair', tier: 5, type: 'Grenade', dedicated: 'Killavolt', location: 'Promethea', area: 'Lectra City', redText: 'Prepare for trouble, and make it double.', ability: 'Rubberized. Throws 2 grenades at once. Increased dmg every bounce', elements: 'F S'},
        {name: 'Ghast Call', tier: 5, type: 'Grenade', dedicated: 'Loot Ghost', location: 'Bloody Harvest Event', area: 'The Heck Hole', redText: 'To you I am past, a story to tell.', ability: 'Throws a ghost which explodes into more ghosts', elements: 'C'},
        {name: 'Rectifier', tier: 5, type: 'Shield', dedicated: 'Sylestro', location: 'Nekrotafeyo', area: 'Tazendeer Ruins', redText: 'You conduit.', ability: 'Shocks nearby enemies while depleted', elements: 'S'},
        {name: 'Phoenix Tears', tier: 5, type: 'Artifact', dedicated: 'Phoenix', location: 'Pandora', area: 'The Splinterlands', redText: 'Rise from the ashes.', ability: 'Gain 100% HP on second wind'},
        {name: 'Rocket Boots', tier: 5, type: 'Artifact', dedicated: 'Blue Fire', quest: 'From a quest in Desolations Edge (Nekrotafeyo)', location: 'Slaughterstar 3000', redText: 'Not that kind.', ability: 'Slide launches homing rockets that deal incendiary dmg', elements: 'Any'},
        {name: 'Splatter Gun', tier: 5, type: 'Artifact', dedicated: 'Road Dog', location: 'Pandora', area: 'The Splinterlands', redText: 'This Is My BOOMSTICK!', ability: '+50% Shotgun damage while sliding', elements: 'Any'},
        {name: 'Static Charge', tier: 5, type: 'Artifact', dedicated: 'Antalope', location: 'Pandora', area: 'Devils Razor', redText: 'Shock me like an electric eel.', ability: 'Slide builds next melee to deal 50% bonus shock dmg. Chains to nearby enemies', elements: 'Any'},
        {name: 'Dragon', tier: 5, type: 'Class Mod', character: 'Amara', dedicated: 'Tink of Cunning', location: 'Ghostlight Beacon', quest: 'Trial of Cunning', redText: 'Fatality.', ability: 'Melee kill triggers Amara\'s action skill augment'},
        {name: 'Elementalist', tier: 5, type: 'Class Mod', character: 'Amara', dedicated: 'Sera of Supremacy', location: 'Hall Obsidian', quest: 'Trial of Supremacy', redText: 'Firmly grasp it.', ability: 'Phasegrasp applies Action Skill Element to nearby enemies'},
        {name: 'Rakk Commander', tier: 5, type: 'Class Mod', character: 'Fl4k', dedicated: 'Sera of Supremacy', location: 'Hall Obsidian', quest: 'Trial of Supremacy', redText: 'Get ready to rakk.', ability: 'Rakk Attack! gains 1 extra charge'},
        {name: 'Shockerator', tier: 5, type: 'Class Mod', character: 'Zane', dedicated: 'Hag of Fervor', location: 'Skydrowned Pulpit', quest: 'Trial of Fervor', redText: 'There\'s a spark between us, can you feel it?'},
        {name: 'Techspert', tier: 5, type: 'Class Mod', character: 'Zane', dedicated: 'Arbalest of Discipline', location: 'Precipice Anchor', quest: 'Trial of Discipline', redText: 'If you love something, set it free.', ability: 'Kill skill: +5% chance on kill to recharge SNTNL cooldown & duration'},

        {name: 'Creeping Death', tier: 6, type: 'Shotgun', dedicated: 'Mother of Grogans', location: 'Eden-6', area: 'The Anvil', redText: 'I creep across the land.', ability: 'Reload creates target for homing grenades the gun shoots', elements: 'C'},
        {name: 'TKs Wave', tier: 6, type: 'Shotgun', dedicated: 'Dumptruck', location: 'Pandora', area: 'The Droughts', redText: 'Ride the wave, dude!', ability: 'Projectiles travel in a wave pattern. Ricochets off surfaces.', elements: 'N F S'},
        {name: 'Bearcat', tier: 6, type: 'AR', dedicated: 'Heckle/Hyde', location: 'Eden-6', area: 'Jakobs Estate', redText: 'I love the smell of popcorn in the morning', ability: 'Launches horizontal row of grenades. 4 ammo/shot', elements: 'Any'},
        {name: 'Hand of Glory', tier: 6, type: 'AR', dedicated: 'Quest Reward', quest: 'The Guns of Reliance', location: 'Eden-6', area: 'Floodmoor Basin', redText: 'By one, by two, by three!', ability: '2-Round burst', elements: 'N'},
        {name: 'Sawbar', tier: 6, type: 'AR', dedicated: 'Borman Nates', location: 'Promethea', area: 'Meridian Outskirts', redText: 'Suppressing Fires!!!', ability: 'Bullets split into 3 projectiles', elements: 'F'},
        {name: 'Vanquisher', tier: 6, type: 'SMG', dedicated: 'Power Troopers', location: 'Promethea', area: 'Atlas HQ', redText: 'Slide forward into your cave.', ability: '20% slide speed increase. Doubles fire rate while sliding', elements: 'Any'},
        {name: 'Girth Blaser', tier: 6, type: 'Pistol', dedicated: 'Deluxe Edition', redText: 'Dont go to pieces on me.', ability: 'Toy gun that shoots foam darts', elements: 'N'},
        {name: 'Hyper-Hydrator', tier: 6, type: 'Pistol', dedicated: 'Deluxe Edition', redText: 'Moister is noice-ter', ability: 'Water gun / Taser. Wet enemies take increased shock dmg', elements: 'S'},
        {name: 'Multi-Tap', tier: 6, type: 'Pistol', m6: true, dedicated: 'Katagawa Ball', location: 'Promethea', area: 'Skywell-27', redText: 'Double the fun.', ability: 'Reloading will fire a Cryo rocket at tagged enemies. Very high fire rate. Fires at all tracked targets at no additional ammo cost.', elements: 'N'},
        {name: 'Scorpio', tier: 6, type: 'Pistol', dedicated: 'Judge Hightower', location: 'Promethea', area: 'Lectra City', redText: 'Mobile oppression for pennies a day.', ability: 'Reload creates Rolands turret', elements: 'N'},
        {name: 'ASMD', tier: 6, type: 'Sniper', dedicated: 'Maxitrillion', location: 'Eden-6', area: 'Voracious Canopy', redText: 'You planning a follow up?', ability: 'Energy shots / Orb. Orb explodes when shot with energy bolt', elements: 'S'},
        {name: 'Cheddar Shredder', tier: 6, type: 'Grenade', dedicated: 'Deluxe Edition', redText: 'Make it rain.', ability: '"Enemies drop a holy metric buttload of cash when damaged"', elements: 'N'},
        {name: 'Diamon Butt Bomb', tier: 6, type: 'Grenade', dedicated: 'Deluxe Edition', redText: 'Bye bye, Li\'l Butt Stallion!', ability: 'Throw Buttstallion with a rainbow explosion', elements: 'N'},
        {name: 'Fastball', tier: 6, type: 'Grenade', dedicated: 'Thunk', location: 'Pandora', area: 'Konrads Hold', redText: 'Forget the curveball Ricky, give him the heater.', ability: 'Throws the grenade like a fast baseball. Explodes on impact', elements: 'Any'},
        {name: 'Scream of Terror', tier: 6, type: 'Shield', dedicated: 'Loot Ghost', location: 'Bloody Harvest Event', area: 'The Heck Hole', redText: 'Behold the flesh and power it holds.', ability: '"Let loose a piercing scream" 14872 nova dmg on shield break.', elements: 'O'},
        {name: 'Whiskey Tango Foxtrot', tier: 6, type: 'Shield', dedicated: 'Crushjaw', location: 'Pandora', area: 'Cathedral of the Twin Gods', redText: 'Situation normal.', ability: 'Nova. 25% chance to drop IEDs when damaged', elements: 'N C S'},
        {name: 'Moxxis Endowment', tier: 6, type: 'Artifact', dedicated: 'Graveward', location: 'Eden-6', area: 'The Floating Tomb', redText: 'Hey, sugar. I got somethin\' for ya', ability: '+10% Combat XP (lvl 57)'},
        {name: 'Pull Out Method', tier: 6, type: 'Artifact', dedicated: 'DJ Deadsk4g', location: 'Pandora', area: 'The Splinterlands', redText: 'Doesn\'t work how you think it does...', ability: 'Slam generates a singularity effect, pulling enemies toward you', elements: 'N S R O'},
        {name: 'Rocketeer', tier: 6, type: 'Class Mod', character: 'Moze', dedicated: 'Arbalest of Discipline', location: 'Precipice Anchor', quest: 'Trial of Discipline', redText: 'Chew \'em up!', ability: 'Auto bear lasts remaining duration. Removes refunded cooldown'},

        {name: 'Iceburger', tier: 0, type: 'Shotgun', dedicated: 'Roaster,The Tenderizer,Joey Ultraviolet', location: 'Revenge of the Cartels,Revenge of the Cartels,Revenge of the Cartels', area: 'Villa Ultraviolet,Villa Ultraviolet,Villa Ultraviolet', redText: '90% of the flavor is under the bun.', ability: 'Shoots continuous fire laser and frozen burgers', elements: 'F'},
        // {name: 'Dream Gun', tier: 0, type: 'Shotgun'},
        {name: 'NoPewPew', tier: 0, type: 'AR', dedicated: 'Roaster,The Tenderizer,Joey Ultraviolet', location: 'Revenge of the Cartels,Revenge of the Cartels,Revenge of the Cartels', area: 'Villa Ultraviolet,Villa Ultraviolet,Villa Ultraviolet', redText: 'Extra, extra spicy.', ability: '3 projectiles/shot. Gradual increase in fire rate. 1 ammo/shot, can be [4 projectiles/shot. 2 ammo/shot]', elements: 'F'},
        // {name: 'Portals and Shite', tier: 0, type: 'AR'},
        {name: 'Needle Gun', tier: 0, type: 'SMG', dedicated: 'Joey Ultraviolet,Josie Byte,Franco Firewall', location: 'Revenge of the Cartels,Revenge of the Cartels,Revenge of the Cartels', area: 'Villa Ultraviolet,Villa Ultraviolet,Villa Ultraviolet', redText: 'Not your average needle.', ability: 'Shooting applies debuff on enemy. [Damage boost on reload]', elements: 'Any'},
        // {name: 'P2P Networker', tier: 0, type: 'SMG'},
        {name: 'Grease Trap', tier: 0, type: 'Pistol', dedicated: 'Roaster,The Tenderizer,Joey Ultraviolet', location: 'Revenge of the Cartels,Revenge of the Cartels,Revenge of the Cartels', area: 'Villa Ultraviolet,Villa Ultraviolet,Villa Ultraviolet', redText: 'EXTREMELY FLAMABLE!', ability: 'Hot Grease (spread shot) / Fire Starter (fireballs)', elements: 'F'},
        // {name: 'Bite Size', tier: 0, type: 'Pistol'},
        // {name: 'RYNAH', tier: 0, type: 'Rocket Launcher'},
        {name: 'Fish Slap', tier: 0, type: 'Grenade', dedicated: 'FISH SLAP!!!,Tyrone Smallums,Joey Ultraviolet', location: 'Revenge of the Cartels,Revenge of the Cartels,Revenge of the Cartels', area: 'Villa Ultraviolet,Villa Ultraviolet,Villa Ultraviolet', redText: 'Say hello to my little fish!', ability: 'Fishslap\'s damage is Melee Damage. Heals shields for 30% of shield dmg dealt. Pre: [Singularity / Elemental +20%dmg +80% chance / Jumping +10% dmg per jump', elements: 'Any'},
        {name: 'Red Card', tier: 0, type: 'Shield', dedicated: 'Gigamind', location: 'Promethea', area: 'Meridian Metroplex', redText: 'All Studs.', ability: 'Sliding drains all shield to deal bonus dmg based on shield strength', elements: 'N C S R O'},
        {name: 'Red Card Re-Charger', tier: 0, type: 'Shield', dedicated: 'Valkyrie Squad', area: 'Midnights Cairn', redText: 'One more kick, with feeling', ability: 'Mix of Red Card & Re-Charger shields', elements: 'F C S R'},
        {name: 'Re-Router', tier: 0, type: 'Shield', dedicated: 'Princess Tarantella II', location: 'Pandora', area: 'The Splinterlands', redText: '', ability: 'Amp shot drains 50% shield for 120% dmg. Dmg returned as HP', elements: 'N F C R'},
        {name: 'Conductor', tier: 0, type: 'Class Mod', character: 'Zane', dedicated: 'World Drop Only', location: 'Xylourgos', redText: 'Half a league onward.', ability: 'Gain up to 25% bonus shock dmg based on remaining AS duration'},
        {name: 'Sapper', tier: 0, type: 'Class Mod', character: 'Moze', dedicated: 'World Drop Only', location: 'Xylourgos', redText: 'To each according to their needs.', ability: 'Gain up to 12% Life Steal. Longer fire duration, greater the lifesteal'},
        {name: 'Stone', tier: 0, type: 'Class Mod', character: 'Amara', dedicated: 'World Drop Only', location: 'Xylourgos', redText: 'She\'s mighty mighty.', ability: 'When hurt, +10% chance to gain Rush stack. +3% dmg reduction/stack'},
        {name: 'Tr4iner', tier: 0, type: 'Class Mod', character: 'Fl4k', dedicated: 'World Drop Only', location: 'Xylourgos', redText: 'This is my cause.', ability: '25% chance for pet to confuse enemy for 20 sec instead of kill'},
    ];
};

export const getTiers = () => {
    return [
        {name: 'Top Tier', tier: 1, color: '#FDD7E5'},
        {name: 'Awesome', tier: 2, color: '#FBB307'},
        {name: 'Great', tier: 3, color: '#8E07FF'},
        {name: 'Good', tier: 4, color: '#397AF2'},
        {name: 'Meh', tier: 5, color: '#2E9E49'},
        {name: 'Straight Trash', tier: 6, color: '#C5C5C5'},
        {name: 'Unranked', tier: 0, color: '#C50001'}
    ];
}

export const getTypes = () => {
    return ['Pistol', 'SMG', 'AR', 'Shotgun', 'Rocket Launcher', 'Sniper', 'Grenade', 'Shield', 'Artifact', 'Class Mod'];
}

export const getModSkills = () => {
    const red = '#E8430E';
    const green = '#3AF00F';
    const blue = '#0B7FF0';
    return {
        'Breaker': [`Jab Cross:${red}`, `Personal Space:${red}`, `Find Your Center:${red}`],
        'Dragon': [`Do Harm:${blue}`, `Remnant:${blue}`, `Restless:${blue}`],
        'Elementalist': [`Wildfire:${red}`, `Infusion:${red}`, `Violent Tapestry:${blue}`],
        'Golden Rule': [`Laid Bare:${blue}`, `Mindfulness:${green}`, `Helping Hand(s):${green}`],
        'Nimbus': [`Conflux:${red}`, `Tempest:${red}`, `Violent Tapestry:${blue}`],
        'Phasezerker': [`Anima:${red}`, `Clarity:${green}`, `Conflux:${red}`],
        'Spiritual Driver': [`Clarity:${green}`, `Helping Hand(s):${green}`, `Mindfulness:${green}`],
        'Stone': [`Awakening:${blue}`, `Do Harm:${blue}`, `Violent Tapestry:${blue}`],

        'Bounty Hunter': [`Frenzy:${blue}`, `Hunters Eye:${red}`, `The Most Dangerous Game: ${red}`],
        'Cosmic Stalker': [`Hunters Eye:${red}`, `Interplanetary Stalker:${red}`, `Big Game:${red}`],
        'DE4DEYE': [`Go For The Eyes:${blue}`, `The Fast And The Furryous:${green}`, `Two F4ng:${red}`],
        'Friend-Bot': [`All My BFFs:${green}`, `Barbaric Yawp:${blue}`, `Psycho Head On A Stick:${blue}`],
        'R4kk P4k': [`Grim Harvest:${red}`, `Head Count:${red}`, `Pack Tactics:${blue}`],
        'Rakk Commander': [`Eager To Impress:${green}`, `Ferocity:${blue}`, `He Bites:${blue}`],
        'Red Fang': [`Eager To Impress:${green}`, `Ferocity:${blue}`, `He Bites:${blue}`],
        'St4ckbot': [`Hunters Eye:${red}`, `The Fast And The Furryous:${green}`, `Pack Tactics:${blue}`],
        'Tr4iner': [`Pack Tactics:${blue}`, `Grim Harvest:${red}`, `Ferocity:${blue}`],

        'Bear Trooper': [`Explosive Punctuation:${blue}`, `Grizzled:${blue}`, `Stainless Steel Bear:${blue}`],
        'Blast Master': [`Pull The Holy Pin:${blue}`, `Redistribution:${green}`, `Vampyr:${blue}`],
        'Bloodletter': [`Desperate Measures:${red}`, `Phalanx Doctrine:${red}`, `Thin Red Line:${red}`],
        'Green Monster': [`Scorching RPMs:${green}`, `Click Click:${green}`, `The Iron Bank:${green}`],
        'Mind Sweeper': [`Fire In The Skag Den:${blue}`, `Redistribution:${green}`, `Torgue Cross Promotion:${blue}`],
        'Raging Bear': [`Deadlines:${blue}`, `Stainless Steel Bear:${blue}`, `Stoke The Embers:${green}`],
        'Rocketeer': [`Cloud Of Lead:${green}`, `Fire In The Skag Den:${blue}`, `Torgue Cross Promotion:${blue}`],
        'Sapper': [`Matched Set:${green}`, `Means Of Destruction:${blue}`, `The Iron Bank:${green}`],

        'Antifreeze': [`Supersonic Man:${red}`, `Violent Momentum:${blue}`, `Violent Speed:${blue}`],
        'Cold Warrior': [`Ready For Action:${green}`, `Synchronicity:${red}`, `Trick Of The Light:${red}`],
        'Conductor': [`Adrenaline:${green}`, `Borrowed Time:${red}`, `Good Misfortune:${blue}`],
        'Executor': [`Good Misfortune:${blue}`, `Playing Dirty:${blue}`, `Violent Violence:${blue}`],
        'Infiltrator': [`Like A Ghost:${red}`, `Supersonic Man:${red}`, `Violent Momentum:${blue}`],
        'Seein Dead': [`Donnybrook:${red}`, `Playing Dirty:${blue}`, `Violent Violence:${blue}`],
        'Shockerator': [`Best Served Cold:${green}`, `Duct Tape Mod:${red}`, `Pocket Full Of Grenades:${red}`],
        'Techspert': [`Ready For Action:${green}`, `Really Expensive Jacket:${green}`, `Rise To The Occasion:${green}`]
    }
}

export const getAnnointments = () => {
    return {
        'Shield': {
            Univeral: [
                'On ASE, movement speed is increased by 5% for 12s',
                'On ASE, regenerate 5% max health per second for 12s',
                'On ASE, Action Skill cooldown rate is increased by 20% for 15s',
                'On ASE, damage taken is reduced by 13% for 12s',
                'On ASE, gain 50% Fire damage with weapons for 10s',
                'On ASE, gain 50% Corrosive damage with weapons for 10s',
                'On ASE, gain 50% Shock damage with weapons for 10s',
                'On ASE, gain 50% Cryo damage with weapons for 10s',
                'On ASE, gain 50% Radiation damage with weapons for 10s',
                'On ASE, melee damage is increased by 100% for 12s',
                'On Action Skill Start, Activate any effects that trigger on shield break or fill',
                'While Action Skill Active, 250% of health damage taken is returned to the attacked as shock damage',
                'On Shield Break, the next shot deals 100% shield capacity as bonus Amp damage',
                'While Sliding, build up energy that refills a portion of your shields. (5% per slide)',
            ],
            Amara: [
                'After using Phaseslam, melee damage is increased by 200% for 10s',
                'After using Phaseslam, damage taken is reduced by 25% and movespeed is increased by 12% for 12s',
                'While Phasegrasp is active, Amara constantly triggers novas',
                'On ASE, 30% of all damage taken is returned to attacker for 12s',
            ],
            Zane: [
                'While Digi-Clone active, regenerate 3% max health/sec',
                'While Barrier is deployed, instantly start recharging your shields',
                'While STNL active, move speed increased by 15%',
            ],
            Moze: [
                'After Exiting Iron Bear, gain 75% increased shields and health for 25s',
                'After Exiting Iron Bear, kills increase Iron Bears cooldown rate by 30% for 30s',
                'When entering and exiting Iron Bear, create a nova that deals damage'
            ],
            Fl4k: [
                'When exiting Fade Away, create a nova that deals 175% damage',
                'Grants an extra charge of Rakk Attack',
            ]
        }, 
        'Weapon': {
            Universal: [
                'On ASE, Weapon Damage is increased by 100% for a short time',
                'On ASE, The next 2 magazines will have 50% additional bonus Fire damage',
                'On ASE, The next 2 magazines will have 50% additional bonus Corrosive damage',
                'On ASE, The next 2 magazines will have 50% additional bonus Shock damage',
                'On ASE, The next 2 magazines will have 50% additional bonus Cryo damage',
                'On ASE, The next 2 magazines will have 50% additional bonus Radiation damage',
                'On ASE, Critical Damage is increased by 25% for a short time',
                'On ASE, Gain 15% Life Steal for a short time',
                'On ASE, Weapon Accuracy & Handling are greatly increased for a short time',
                'On ASE, Fire rate is increased by 11%, & reload speed by 26% for a short time',
                'On ASE, Weapon Status Effect Damage & Chance are increased by 75% for a short time',
                'On ASE, 100% increased melee damage',
                'On ASE, 20% increased action skill cooldown rate',
                'On ASE, Deal 125% more Weapon Damage to Badass, Named and Boss enemies for a short time',
                'On ASE, Splash Damage is increased by 125% for a short time',
                'On ASE, Projectile Speed is increased by 100% for a short time',
                'On ASE, Spawn a healing pool for several seconds',
                'On ASE, Create a cyber spike that damages nearby enemies',
                'While Airborne, Crit damage increased by 25%',
                'While Airborne, Fire rate is increased by 25%',
                'While Airborne, Damage is increased by 30%',
                'While Airborne, Accuracy and Handling are increased by 75%',
                'While Sliding, Damage is increased by 40%',
                'While Sliding, Accuracy and Handling are increased by 50%',
                'While Sliding, Fire Rate is increased by 25%',
                'Consecutive Hits increase Weapon Damage by 1% per hit, misses remove all bonuses',
                'Killing an enemy grants 5% Weapon Damage and Reload Speed for 25 seconds, this effect stacks',
                'While enemies are below 25% Health, gain 50% increased Weapon Damage',
                'While Action Skill is Active, Weapon damage is increased by 200%',
                'While Action Skill is Active, Reduce all incoming damage by a small amount',
                'While Action Skill is Active, Constantly trigger novas that deal damage',
                'While Action Skill is Active, Deal 75% more weapon damage to Badass, Named and Boss enemies',
                'Gain 300% increased weapon damage against enemies above 90% health',
                'While under 50% health, deal 150% bonus radiation damage'
            ],
            Amara: [
                'After Phasegrasping an enemy, Weapon Accuracy and Handling are greatly increased',
                'After using Phasecast, Weapon Damage is increased by 250% for a short time',
                'After using Phasecast, Status Effect Chance is increased by 50% for a short time',
                'After using Phaseslam, Weapon Damage is increased by 300% for a short time',
                'After using Phaseslam, Melee Damage is increased by 200% for a short time',
                'After using Phaseslam, damage taken is reduced by 20% and movespeed is increased by 12%',
                'While Phasegrasp is active, 71% decreased weapon charge time and 12% increased movement speed',
                'On ASE, deal 40% bonus radiation damage for a short time',
            ],
            Zane: [
                'After swapping places with your Digi-Clone, Weapon Damage is increased by 130% for a short time',
                'After swapping places with your Digi-Clone, your weapon is reloaded',
                'While Digi-Clone is active, regenerate 12% of magazine ammo per second',
                'While Barrier is active, Accuracy is increased by 60%, and Critical Hit damage is increased by 70%',
                'While Barrier is active, Status Effect Chance is increased by 50%',
                'While SNTNL is active, Fire Rate is increased by 9% and Reload Speed by 23%',
                'While SNTNL is active, Gain 100% of damage as bonus Cryo damage',
            ],
            Moze: [
                'After exiting Iron Bear, the next 3 magazines will have 33% incrased reload speed and 67% increased handling',
                'After exiting Iron Bear, the next 2 magazines will have 125% bonus incendiary damage',
                'After exiting Iron Bear, 160% increased splash damage for 18 seconds',
                'After exiting Iron Bear, kills increase Iron Bear’s cooldown rate by 30%',
                'After exiting Iron Bear, do not consume ammo for 5s',
                'After exiting Iron Bear, the next 2 magazines will have 10% increased fire rate and 20% critical damage',
                'While Auto Bear is active, 75% bonus incendiary damage',
                'Elemental crits can cause status effects of that element to explode, creating nova that deals 500% of the effects damage',
                'While Auto Bear is active, constantly regenerate 8% of magazine size per second'
            ],
            Fl4k: [
                'After using attack command, gain 30% lifesteal for 8s',
                'After using Attack command, gain 8% movement speed for 6s',
                'After using rakk attack, gain 50% critical hit damage for 8s',
                'While fade away is active, gain greatly increased accuracy and handling for 20s',
                'While gamma burst is active gain 115% bonus radiation damage',
                'On Fade Away End, Trigger non-elemental nova',
                'Enemies Damaged by Rakk Attak take 100% increased damage for 10s',
                'Grants an extra chage of rakk attack',
            ]
        },
        'Grenade': {
            Universal: [
                'On Action Skill Start, regenerate 1 grenade',
                'While Action Skill Active, Grenade damage is increased by 150%',
                'On ASE, The next 2 magazines will have 50% additional bonus Fire damage.',
                'On ASE, The next 2 magazines will have 50% additional bonus Corrosive damage.',
                'On ASE, The next 2 magazines will have 50% additional bonus Shock damage.',
                'On ASE, The next 2 magazines will have 50% additional bonus Cryo damage.',
                'On ASE, The next 2 magazines will have 50% additional bonus Radiation damage.',
                'On grenade thrown, weapon, grenade and Action Skill Damage are increased by 25% for 6s',
            ],
            Moze: [
                'While Iron Bear is active, taking damage has a 20% chance to spawn a grenade each 8s',
            ],
        }
    };
}

export const getGrenadeEffects = () => {
    return [
        'Lobbed', 'Longbow', 'Homing', 'Rubberized',
        'Impact', 'Exploder', 'Sticky',
        'Artillery', 'Bouncy', 'Jumping', 'Rain', 'MIRV', 'Mini MIRV', 'Singularity', 'Chiller', 'Corrupter', 'Blight', 'Flamer', 'Tesla',
        'Roider', 'Link', 'Large', 'Nuke', 'Divider',
        'Generator', 'Transfusion', 'Force', 'Money', 'Elemental Damage'
    ];
}

export const getShieldEffects = () => {
    return [
        'Absorb', 'Adaptive', 'Adrenaline', 'Amp', 'Booster', 'Brimming', 'Capacity', 'Delay', 'Devourer', 'Fleet', 'Fortify Charge', 'Health', 'Health Charge', 
        'Nova', 'Power Charge', 'Projected', 'Quick-Charge', 'Recharger', 'Reflect', 'Resistant', 'Roid', 'Safe-Space', 'Spike', 'Staw Man', 'Trigger Happy', 'Turtle', 'Vagabond'
    ];
}

export const getArtifactPrefixes = () => {
    return [
        {name: 'Atom Balm'},
        {name: 'Berzerker'},
        {name: 'Cauterizing'},
        {name: 'Caustic Coast'},
        {name: 'Corrosive Stone'},
        {name: 'Cutpurse'},
        {name: 'Electric Slide'},
        {name: 'Elemental Projector'},
        {name: 'Fire Stone'},
        {name: 'Flesh Melter'},
        {name: 'Hot Drop'},
        {name: 'Ice Breaker'},
        {name: 'Ice Spiker'},
        {name: 'Knife Drain'},
        {name: 'Last Stand'},
        {name: 'Loot Expanding'},
        {name: 'Mind Melt'},
        {name: 'Radiodead'},
        {name: 'Rear Ender'},
        {name: 'Shock Stone	'},
        {name: 'Spark Plug'},
        {name: 'Snowdrift'},
        {name: 'Toxic Revenger'},
    ];
}

export const getArtifactStats = () => {
    return [
        {name: 'Action Skill Cooldown Rate'},
        {name: 'Area-Of-Effect Damage'},
        {name: 'Cryo Damage'},
        {name: 'Cryo Efficiency'},
        {name: 'Cryo Resistance'},
        {name: 'Corrosive Damage'},
        {name: 'Corrosive Resistance'},
        {name: 'Electrocute Chance'},
        {name: 'Electrocute Resistance'},
        {name: 'Elemental Resistance'},
        {name: 'Experience Gained From Combat'},
        {name: 'FFYL Duration'},
        {name: 'FFYL Movement Speed'},
        {name: 'Grenade Damage'},
        {name: 'Health/sec', prefix: 'Regenerates +', suffix: ''},
        {name: 'Ignite Change'},
        {name: 'Incendiary Damage'},
        {name: 'Incendiary Resistance'},
        {name: 'Irradiate Chance'},
        {name: 'Luck', suffix: ''},
        {name: 'Magazine Size'},
        {name: 'Max Health', suffix: ''},
        {name: 'Max Shield', suffix: ''},
        {name: 'Melee Damage'},
        {name: 'Movement Speed'},
        {name: 'Radiation Damage'},
        {name: 'Radiation Resistance'},
        {name: 'Shield Recharge Rate'},
        {name: 'Shield Recharge Delay', prefix: '-'},
        {name: 'Shock Damage'},
        {name: 'Shock Resistance'},
        {name: 'Shotgun Damage'},
        {name: 'SMG Damage'},
        {name: 'Sniper Damage'},
        {name: 'Weapon Accuracy'},
    ];
}

export const getModStats = () => {
    return [
        {name: 'Action Skill Cooldown Rate'},
        {name: 'Assault Rifle Damage'},
        {name: 'Atlas Weapon Critical Damage'},
        {name: 'Atlas Weapon Damage'},
        {name: 'Altas Weapon Fire Rate'},
        {name: 'Atlas Weapon Reload Speed'},
        {name: 'COV Weapon Accuracy'},
        {name: 'COV Weapon Critical Damage'},
        {name: 'COV Weapon Damage'},
        {name: 'COV Weapon Fire Rate'},
        {name: 'Corrosive Resistance'},
        {name: 'Cryo Resistance'},
        {name: 'Dahl Weapon Accuracy'},
        {name: 'Dahl Weapon Critical Damage'},
        {name: 'Dahl Weapon Damage'},
        {name: 'Dahl Weapon Fire Rate'},
        {name: 'Dahl Weapon Reload Speed'},
        {name: 'Damage Reduction', prefix: '-'},
        {name: 'Grenade Capacity', suffix: ''},
        {name: 'Grenade Damage'},
        {name: 'Grenade Radius'},
        {name: 'Health Regen', suffix: ''},
        {name: 'Heavy Weapon Damage'},
        {name: 'Hyperion Weapon Critical Damage'},
        {name: 'Hyperion Weapon Damage'},
        {name: 'Hyperion Weapon Fire Rate'},
        {name: 'Hyperion Weapon Reload Speed'},
        {name: 'Incendiary Resistance'},
        {name: 'Jakobs Weapon Accuracy'},
        {name: 'Jakobs Weapon Critical Damage'},
        {name: 'Jakobs Weapon Damage'},
        {name: 'Jakobs Weapon Reload Speed'},
        {name: 'Maliwan Weapon Accuracy'},
        {name: 'Maliwan Weapon Critical Damage'},
        {name: 'Maliwan Weapon Damage'},
        {name: 'Maliwan Weapon Fire Rate'},
        {name: 'Maliwan Weapon Reload Speed'},
        {name: 'Max Health', suffix: ''},
        {name: 'Melee Damage'},
        {name: 'Pistol Damage'},
        {name: 'Radiation Resistance'},
        {name: 'Shield Capacity', suffix: ''},
        {name: 'Shield Recharge Delay', prefix: '-'},
        {name: 'Shield Recharge Rate'},
        {name: 'Shock Resistance'},
        {name: 'Shotgun Damage'},
        {name: 'SMG Damage'},
        {name: 'Sniper Rifle Damage'},
        {name: 'Splash Damage'},
        {name: 'Splash Damage Radius'},
        {name: 'Tediore Weapon Accuracy'},
        {name: 'Tediore Weapon Damage'},
        {name: 'Tediore Weapon Fire Rate'},
        {name: 'Tediore Weapon Reload Speed'},
        {name: 'Torgue Weapon Accuracy'},
        {name: 'Torgue Weapon Damage'},
        {name: 'Torgue Weapon Projectile Speed'},
        {name: 'Torgue Weapon Reload Speed'},
        {name: 'Vladof Weapon Accuracy'},
        {name: 'Vladof Weapon Damage'},
        {name: 'Vladof Weapon Fire Rate'},
        {name: 'Vladof Weapon Reload Speed'},
        {name: 'Weapon Accuracy'},
        {name: 'Weapon Damage'},
        {name: 'Weapon Charge Speed'},
        {name: 'Weapon Critical Damage'},
        {name: 'Weapon Fire Rate'},
        {name: 'Weapon Handling'},
        {name: 'Weapon Magazine Size'},
        {name: 'Weapon Reload Speed'},
    ];
}




export default getItems;